// SPDX-FileCopyrightText: 2026 Alexandre Gomes Gaigalas <alganet@gmail.com>
//
// SPDX-License-Identifier: ISC

use crate::lint::Violation;
use crate::rules::Rule;

/// Ensure OAuth 2.0 authorization code flows correlate the `state` parameter
/// between the initial authorization request and the subsequent callback.
///
/// The `state` parameter is an opaque value generated by the client and
/// included in the authorization request (with `response_type=code`).  RFC 6749
/// §4.1.1 RECOMMENDS (SHOULD) that clients use `state`, and requires the
/// authorization server to echo the same `state` value back only if it was
/// present in the request.  This rule treats `state` as required for code flows
/// to help prevent CSRF and replay attacks.
///
/// The rule watches outgoing requests.  It records any `state` values seen in
/// authorization requests and, when a later request includes an OAuth `code`,
/// verifies a matching `state` was observed earlier.  Missing or mismatched
/// `state` parameters trigger violations.
///
/// Correlation is performed only within the transaction history provided by
/// the engine for this rule. In the current engine this typically includes
/// requests to the same resource/origin as the one being checked; requests to
/// other origins (for example, an IdP on a different host) may not be
/// available for correlation, depending on query configuration.
pub struct StatefulOauth2CodeFlow;

impl Rule for StatefulOauth2CodeFlow {
    fn id(&self) -> &'static str {
        "stateful_oauth2_code_flow"
    }

    fn scope(&self) -> crate::rules::RuleScope {
        // Only examines outgoing requests; does not depend on server behaviour.
        crate::rules::RuleScope::Client
    }

    fn check_transaction(
        &self,
        tx: &crate::http_transaction::HttpTransaction,
        history: &crate::transaction_history::TransactionHistory,
        cfg: &crate::config::Config,
    ) -> Option<Violation> {
        let config = crate::rules::parse_rule_config(cfg, self.id()).ok()?;
        let req_uri = &tx.request.uri;
        // simple query extraction: portion after '?' if present, ignoring any
        // URI fragment (`#...`) which is not part of the query string.
        let query = req_uri.split_once('?').map(|x| x.1).unwrap_or("");
        let query = query.split('#').next().unwrap_or(query);

        let params = crate::helpers::uri::parse_query_string(query);

        // helper to lookup a parameter by name (first occurrence)
        fn get_param<'a>(pairs: &'a [(String, String)], key: &str) -> Option<&'a String> {
            for (k, v) in pairs {
                if k == key {
                    return Some(v);
                }
            }
            None
        }

        // detect authorization request
        if let Some(rt) = get_param(&params, "response_type") {
            if rt == "code" {
                // must have state; treat empty or whitespace-only as missing
                match get_param(&params, "state") {
                    Some(s) if !s.trim().is_empty() => {
                        // OK
                    }
                    _ => {
                        return Some(Violation {
                            rule: self.id().into(),
                            severity: config.severity,
                            message: "OAuth2 authorization request with response_type=code missing or empty state parameter".into(),
                        });
                    }
                }
                // nothing else to check for the request itself
            }
        }

        // detect callback carrying authorization code
        if get_param(&params, "code").is_some() {
            match get_param(&params, "state") {
                Some(state_val) if !state_val.trim().is_empty() => {
                    // look for prior authorization request with same state
                    let mut seen = false;
                    for prev in history.iter() {
                        let prev_q = prev.request.uri.split_once('?').map(|x| x.1).unwrap_or("");
                        let prev_q = prev_q.split('#').next().unwrap_or(prev_q);
                        let prev_params = crate::helpers::uri::parse_query_string(prev_q);
                        if let Some(rt2) = get_param(&prev_params, "response_type") {
                            if rt2 == "code" {
                                if let Some(ps) = get_param(&prev_params, "state") {
                                    if ps == state_val {
                                        seen = true;
                                        break;
                                    }
                                }
                            }
                        }
                    }
                    if !seen {
                        return Some(Violation {
                            rule: self.id().into(),
                            severity: config.severity,
                            message: "OAuth2 authorization callback used a state value that was not seen in a prior request".into(),
                        });
                    }
                }
                _ => {
                    return Some(Violation {
                        rule: self.id().into(),
                        severity: config.severity,
                        message: "OAuth2 authorization callback missing or empty state parameter"
                            .into(),
                    });
                }
            }
        }

        None
    }

    fn description(&self) -> &'static str {
        "The OAuth 2.0 authorization code flow **recommends** (SHOULD) that clients generate and include a `state` parameter in the initial authorization request to bind the request and eventual callback.  When the server echoes an authorization `code`, it is required to return the same `state` value **only if** the request contained one (RFC 6749 §4.1.1).  The parameter is optional in the spec, but omitting it leaves the flow vulnerable to CSRF/replay attacks.\n\nThis rule therefore treats a request or callback that either lacks a `state` parameter or provides an empty/whitespace value as a violation, enforcing a best‑practice requirement that a meaningful state be correlated.\n\nThis value prevents cross-site request forgery (CSRF) and replay attacks by ensuring the callback corresponds to a request the client actually initiated. Without this correlation, a malicious site could trick the user agent into sending a `code` it did not request, allowing the attacker to hijack the authorization grant.\n\nThe lint rule observes outgoing requests from a user agent.  It records any `state` seen in authorization requests and, when a later request carries an authorization `code`, verifies that a matching `state` occurred previously. Violations are raised for missing `state` parameters in either direction or when the callback contains a value not previously observed.\n\nThe check does not assume the authorization request and callback share a common origin; the redirect is typically to the client's own domain while the initial request targets the identity provider."
    }

    fn rfc_reference(&self) -> Option<&'static str> {
        Some("[RFC 6749 §4.1.1 — Authorization Request](https://www.rfc-editor.org/rfc/rfc6749.html#section-4.1.1)")
    }

    fn examples(&self) -> &'static [crate::rules::Example] {
        use crate::rules::{Compliance, Example};
        &[
            Example {
                compliance: Compliance::Compliant,
                snippet: "> GET /authorize?response_type=code&client_id=1&state=xyz HTTP/1.1\n> Host: idp.example.com\n\n< HTTP/1.1 302 Found\n< Location: https://app.example.com/callback?code=abc&state=xyz",
            },
            Example {
                compliance: Compliance::NonCompliant,
                snippet: "> GET /authorize?response_type=code&client_id=1 HTTP/1.1\n> Host: idp.example.com",
            },
            Example {
                compliance: Compliance::NonCompliant,
                snippet: "> GET /callback?code=abc HTTP/1.1\n> Host: app.example.com",
            },
            Example {
                compliance: Compliance::NonCompliant,
                snippet: "> GET /callback?code=abc&state=wrong HTTP/1.1\n> Host: app.example.com",
            },
        ]
    }
}

/// Registers this rule into the engine's auto-collected catalogue.
#[linkme::distributed_slice(crate::rules::REGISTERED_RULES)]
static REGISTRATION: &dyn crate::rules::Rule = &StatefulOauth2CodeFlow;

#[cfg(test)]
mod tests {
    use super::*;
    use crate::test_helpers;

    fn make_tx(uri: &str) -> crate::http_transaction::HttpTransaction {
        let mut tx = test_helpers::make_test_transaction();
        tx.request.uri = uri.to_string();
        tx
    }

    #[test]
    fn auth_request_without_state_flagged() {
        let rule = StatefulOauth2CodeFlow;
        let tx = make_tx("https://idp.example.com/authorize?response_type=code&client_id=1");
        let history = crate::transaction_history::TransactionHistory::empty();
        let v = rule
            .check_transaction(
                &tx,
                &history,
                &crate::test_helpers::make_test_config_with_enabled_rules(&[
                    "stateful_oauth2_code_flow",
                ]),
            )
            .unwrap();
        assert!(v.message.contains("missing or empty state"));
    }

    #[test]
    fn auth_request_with_state_ok() {
        let rule = StatefulOauth2CodeFlow;
        let tx = make_tx("https://idp.example.com/authorize?response_type=code&state=xyz");
        let history = crate::transaction_history::TransactionHistory::empty();
        assert!(rule
            .check_transaction(
                &tx,
                &history,
                &crate::test_helpers::make_test_config_with_enabled_rules(&[
                    "stateful_oauth2_code_flow"
                ]),
            )
            .is_none());
    }

    #[test]
    fn callback_without_state_flagged() {
        let rule = StatefulOauth2CodeFlow;
        let tx = make_tx("https://app.example.com/callback?code=abc");
        let history = crate::transaction_history::TransactionHistory::empty();
        let v = rule
            .check_transaction(
                &tx,
                &history,
                &crate::test_helpers::make_test_config_with_enabled_rules(&[
                    "stateful_oauth2_code_flow",
                ]),
            )
            .unwrap();
        assert!(v.message.contains("missing or empty state"));
    }

    #[test]
    fn callback_with_unseen_state_flagged() {
        let rule = StatefulOauth2CodeFlow;
        let tx = make_tx("https://app.example.com/callback?code=abc&state=xyz");
        let history = crate::transaction_history::TransactionHistory::empty();
        let v = rule
            .check_transaction(
                &tx,
                &history,
                &crate::test_helpers::make_test_config_with_enabled_rules(&[
                    "stateful_oauth2_code_flow",
                ]),
            )
            .unwrap();
        assert!(v.message.contains("not seen"));
    }

    #[test]
    fn callback_with_matching_state_ok() {
        let rule = StatefulOauth2CodeFlow;
        // initial auth request earlier in history
        let history = crate::transaction_history::TransactionHistory::new(vec![make_tx(
            "https://idp.example.com/authorize?response_type=code&state=xyz",
        )]);
        let tx = make_tx("https://app.example.com/callback?code=abc&state=xyz");
        assert!(rule
            .check_transaction(
                &tx,
                &history,
                &crate::test_helpers::make_test_config_with_enabled_rules(&[
                    "stateful_oauth2_code_flow"
                ]),
            )
            .is_none());
    }

    #[test]
    fn auth_and_callback_without_code_does_not_check_state() {
        let rule = StatefulOauth2CodeFlow;
        // a request with state but not response_type=code shouldn't trigger
        let tx = make_tx("https://example.com/foo?state=xyz");
        let history = crate::transaction_history::TransactionHistory::empty();
        assert!(rule
            .check_transaction(
                &tx,
                &history,
                &crate::test_helpers::make_test_config_with_enabled_rules(&[
                    "stateful_oauth2_code_flow"
                ]),
            )
            .is_none());
    }

    #[test]
    fn auth_and_callback_with_fragments_are_handled() {
        let rule = StatefulOauth2CodeFlow;
        // auth request has fragment after query, should still record state
        let history = crate::transaction_history::TransactionHistory::new(vec![make_tx(
            "https://idp.example.com/authorize?response_type=code&state=foo#frag",
        )]);
        let tx = make_tx("https://app.example.com/callback?code=abc&state=foo#bar");
        assert!(rule
            .check_transaction(
                &tx,
                &history,
                &crate::test_helpers::make_test_config_with_enabled_rules(&[
                    "stateful_oauth2_code_flow"
                ]),
            )
            .is_none());
    }

    #[test]
    fn auth_request_fragment_missing_state_flagged() {
        let rule = StatefulOauth2CodeFlow;
        let tx = make_tx("https://idp.example.com/authorize?response_type=code#frag");
        let history = crate::transaction_history::TransactionHistory::empty();
        let v = rule
            .check_transaction(
                &tx,
                &history,
                &crate::test_helpers::make_test_config_with_enabled_rules(&[
                    "stateful_oauth2_code_flow",
                ]),
            )
            .unwrap();
        assert!(v.message.contains("missing or empty state"));
    }

    #[test]
    fn empty_state_value_flagged_both_sides() {
        let rule = StatefulOauth2CodeFlow;
        // auth request with empty state
        let tx1 = make_tx("https://idp.example.com/authorize?response_type=code&state=");
        let history = crate::transaction_history::TransactionHistory::new(vec![tx1.clone()]);
        // callback with empty state should flag missing or empty
        let tx2 = make_tx("https://app.example.com/callback?code=123&state=");
        let v = rule
            .check_transaction(
                &tx1,
                &crate::transaction_history::TransactionHistory::empty(),
                &crate::test_helpers::make_test_config_with_enabled_rules(&[
                    "stateful_oauth2_code_flow",
                ]),
            )
            .unwrap();
        assert!(v.message.contains("missing or empty state"));
        let v2 = rule
            .check_transaction(
                &tx2,
                &history,
                &crate::test_helpers::make_test_config_with_enabled_rules(&[
                    "stateful_oauth2_code_flow",
                ]),
            )
            .unwrap();
        assert!(v2.message.contains("missing or empty state"));
    }

    #[test]
    fn validate_rules_with_valid_config() {
        let mut cfg = crate::config::Config::default();
        crate::test_helpers::enable_rule(&mut cfg, "stateful_oauth2_code_flow");
        crate::rules::validate_rules(&cfg).unwrap();
    }
}
