// SPDX-FileCopyrightText: 2026 Alexandre Gomes Gaigalas <alganet@gmail.com>
//
// SPDX-License-Identifier: ISC

//! Generates the `pub mod` declarations for every leaf rule in `src/rules/`.
//!
//! Each rule module self-registers into the engine's `REGISTERED_RULES` /
//! `REGISTERED_PROTOCOL_RULES` distributed slices (see `src/rules/mod.rs`), so
//! the only remaining bookkeeping is declaring the modules. Rather than
//! hand-maintain ~180 `pub mod` lines, we discover the files at build time and
//! emit the declarations into `$OUT_DIR/rule_modules.rs`, which `rules/mod.rs`
//! includes. Adding a rule is then just creating one file in `src/rules/`.
//!
//! The declarations use an absolute `#[path]` so module resolution works from
//! the included file (a bare `pub mod foo;` inside an `include!`d file would
//! resolve relative to `$OUT_DIR`, not the source tree).

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");
    let rules_dir = Path::new(&manifest_dir).join("src").join("rules");

    // Rebuild whenever a rule file is added, removed, or renamed.
    println!("cargo:rerun-if-changed={}", rules_dir.display());

    let mut modules: Vec<String> = Vec::new();
    for entry in fs::read_dir(&rules_dir).expect("cannot read src/rules") {
        let path = entry.expect("bad dir entry").path();
        if path.extension().and_then(|e| e.to_str()) != Some("rs") {
            continue;
        }
        let stem = path
            .file_stem()
            .and_then(|s| s.to_str())
            .expect("non-utf8 rule file name");
        if stem == "mod" {
            continue;
        }
        modules.push(stem.to_string());
    }
    // Sort for a stable, reproducible generated file (build determinism).
    modules.sort();

    let mut out = String::from(
        "// @generated by build.rs from src/rules/*.rs — do not edit.\n\
         // Each module self-registers into REGISTERED_RULES / \
         REGISTERED_PROTOCOL_RULES.\n",
    );
    for m in &modules {
        let abs = rules_dir.join(format!("{m}.rs"));
        out.push_str(&format!(
            "#[path = {:?}]\npub mod {m};\n",
            abs.to_str().expect("non-utf8 rule path"),
        ));
    }

    let dest = Path::new(&env::var("OUT_DIR").expect("OUT_DIR not set")).join("rule_modules.rs");
    fs::write(&dest, out).expect("cannot write generated rule_modules.rs");
}
