// SPDX-FileCopyrightText: 2026 Alexandre Gomes Gaigalas <alganet@gmail.com>
//
// SPDX-License-Identifier: ISC

//! The IANA "HTTP Authentication Schemes" registry, as last updated on 2025-02-18.
//!
//! Every scheme name, folded to lowercase and sorted.
//!
//! Generated by `just genregistries` from what IANA publishes below, which
//! is the only way this file should change:
//!
//! - <https://www.iana.org/assignments/http-authschemes/authschemes.csv>

// cite(RFC 9110 § 16.4.1): "The "Hypertext Transfer Protocol (HTTP) Authentication Scheme Registry" defines the namespace for the authentication schemes in challenges and credentials."
pub(super) const NAMES: &[&str] = &[
    "basic",
    "bearer",
    "concealed",
    "digest",
    "dpop",
    "gnap",
    "hoba",
    "mutual",
    "negotiate",
    "oauth",
    "privatetoken",
    "scram-sha-1",
    "scram-sha-256",
    "vapid",
];
