// SPDX-FileCopyrightText: 2026 Alexandre Gomes Gaigalas <alganet@gmail.com>
//
// SPDX-License-Identifier: ISC

//! The IANA registries a rule asks membership of, carried as snapshots.
//!
//! **A finding named `_unregistered` is a claim about a registry**, and three
//! entries make it: `media_type_unregistered`, `charset_unregistered` and
//! `auth_scheme_unregistered`. Each was answered by a short list shipped in the
//! rule's configuration instead, so every registered name the list left out was
//! reported as unregistered: `application/pdf`, `text/markdown`, `Shift_JIS`,
//! `windows-1252`, `Negotiate`, `DPoP`. A list short enough to read in a config
//! file cannot be the registry, and the registry is what the entries name.
//!
//! The files beside this one are generated by `just genregistries` and headed
//! with the date IANA gives for each registry's last update. What a deployment
//! knowingly uses beyond them is the rule's `allowed` option, which adds to the
//! registry and never replaces it.
//!
//! **The field-name registry is asked a different question: which type.** RFC
//! 9651 § 4.2 parses a field value given a `field_type`, and nothing on the
//! wire carries one, so a reader that does not know it can only ask whether
//! the value parses as *some* type. The registry's Structured Type column is
//! where the type is published.

mod auth_schemes;
mod charsets;
mod media_types;
mod structured_types;

/// Whether a sorted, lowercased snapshot holds `name` under any casing.
///
/// Every name is stored folded to lowercase, because each of the three
/// vocabularies is matched without regard to case.
// cite(RFC 9110 § 8.3.1): "The type and subtype tokens are case-insensitive."
// cite(RFC 9110 § 8.3.2): "In both cases, charset names are matched case-insensitively."
// cite(RFC 9110 § 11.1): "It uses a case-insensitive token to identify the authentication scheme"
fn holds(names: &[&str], name: &str) -> bool {
    names
        .binary_search(&name.to_ascii_lowercase().as_str())
        .is_ok()
}

/// Whether the Media Types registry lists `type_/subtype`.
///
/// The pair is asked, not a string the caller assembled: a registration is a
/// template naming one top-level type and one subtype, and a `+suffix` or a
/// wildcard is neither.
pub fn media_type_registered(type_: &str, subtype: &str) -> bool {
    holds(media_types::NAMES, &format!("{type_}/{subtype}"))
}

/// Whether the Character Sets registry lists `name` as a charset's name, its
/// preferred MIME name, or one of its aliases.
///
/// An alias is a registered name: the registry lists it so that a recipient
/// can recognise it, and `latin1` names ISO-8859-1 as surely as the preferred
/// spelling does.
pub fn charset_registered(name: &str) -> bool {
    holds(charsets::NAMES, name)
}

/// Whether the HTTP Authentication Scheme registry lists `name`.
pub fn auth_scheme_registered(name: &str) -> bool {
    holds(auth_schemes::NAMES, name)
}

/// The three `field_type`s RFC 9651 § 4.2 parses a field value as.
// cite(RFC 9651 § 4.2): "Given an array of bytes as input_bytes that represent the chosen field's field-value (which is empty if that field is not present) and field_type (one of "dictionary", "list", or "item"), return the parsed field value."
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum StructuredType {
    Item,
    List,
    Dictionary,
}

/// The Structured Type the HTTP Field Name registry gives the field `name`,
/// if its column names one of the three.
///
/// `None` for a field the column leaves blank, which is most of them, and for
/// a cell naming something that is no `field_type`: the generator leaves such
/// a field out and says so.
// cite(RFC 9110 § 5.1): "Field names are case-insensitive and ought to be registered within the "Hypertext Transfer Protocol (HTTP) Field Name Registry"; see Section 16.3.1."
pub fn structured_type(name: &str) -> Option<StructuredType> {
    [
        (structured_types::ITEMS, StructuredType::Item),
        (structured_types::LISTS, StructuredType::List),
        (structured_types::DICTIONARIES, StructuredType::Dictionary),
    ]
    .into_iter()
    .find_map(|(names, ty)| holds(names, name).then_some(ty))
}

#[cfg(test)]
mod tests {
    use super::*;
    use rstest::rstest;

    /// The lookup is a binary search, so a snapshot out of order or holding an
    /// uppercase byte answers "unregistered" for a name it lists. The generator
    /// sorts and folds; this is what holds a hand edit to the same standard.
    #[rstest]
    #[case::media_types(media_types::NAMES)]
    #[case::charsets(charsets::NAMES)]
    #[case::auth_schemes(auth_schemes::NAMES)]
    #[case::structured_items(structured_types::ITEMS)]
    #[case::structured_lists(structured_types::LISTS)]
    #[case::structured_dictionaries(structured_types::DICTIONARIES)]
    fn a_snapshot_is_folded_sorted_and_unique(#[case] names: &[&str]) {
        for pair in names.windows(2) {
            assert!(
                pair[0] < pair[1],
                "{:?} is not before {:?}",
                pair[0],
                pair[1]
            );
        }
        for name in names {
            assert_eq!(*name, name.to_ascii_lowercase());
        }
    }

    #[rstest]
    #[case("application", "pdf", true)]
    #[case("text", "markdown", true)]
    #[case("multipart", "mixed", true)]
    #[case("TEXT", "HTML", true)]
    #[case("application", "protobuf", true)]
    #[case("application", "x-protobuf", false)]
    #[case("httpd", "unix-directory", false)]
    #[case("image", "x-icon", false)]
    #[case("application", "+json", false)]
    #[case("*", "*", false)]
    fn media_types_are_the_registrys(
        #[case] type_: &str,
        #[case] subtype: &str,
        #[case] expected: bool,
    ) {
        assert_eq!(media_type_registered(type_, subtype), expected);
    }

    #[rstest]
    #[case("utf-8", true)]
    #[case("UTF-8", true)]
    #[case("Shift_JIS", true)]
    #[case("windows-1252", true)]
    #[case("latin1", true)]
    #[case("utf8", false)]
    #[case("cp1252", false)]
    fn charsets_are_the_registrys(#[case] name: &str, #[case] expected: bool) {
        assert_eq!(charset_registered(name), expected);
    }

    #[rstest]
    #[case("Basic", true)]
    #[case("negotiate", true)]
    #[case("DPoP", true)]
    #[case("SCRAM-SHA-256", true)]
    #[case("X-MyAuth", false)]
    #[case("AidLogin", false)]
    fn auth_schemes_are_the_registrys(#[case] name: &str, #[case] expected: bool) {
        assert_eq!(auth_scheme_registered(name), expected);
    }

    /// A field is registered with one type, so the three lists are disjoint;
    /// a name in two would be read as whichever list is asked first.
    #[test]
    fn a_field_has_one_structured_type() {
        for item in structured_types::ITEMS {
            assert!(!holds(structured_types::LISTS, item), "{item}");
            assert!(!holds(structured_types::DICTIONARIES, item), "{item}");
        }
        for list in structured_types::LISTS {
            assert!(!holds(structured_types::DICTIONARIES, list), "{list}");
        }
    }

    #[rstest]
    #[case("Accept-CH", Some(StructuredType::List))]
    #[case("cache-status", Some(StructuredType::List))]
    #[case("CDN-Cache-Control", Some(StructuredType::Dictionary))]
    #[case("Priority", Some(StructuredType::Dictionary))]
    #[case("Incremental", Some(StructuredType::Item))]
    #[case("Origin-Agent-Cluster", Some(StructuredType::Item))]
    #[case("Sec-Fetch-Storage-Access", None)] // its cell reads `Token`
    #[case("Reporting-Endpoints", None)] // its cell is blank
    #[case("Cache-Control", None)]
    fn structured_types_are_the_registrys(
        #[case] name: &str,
        #[case] expected: Option<StructuredType>,
    ) {
        assert_eq!(structured_type(name), expected);
    }
}
