// SPDX-FileCopyrightText: 2026 Alexandre Gomes Gaigalas <alganet@gmail.com>
//
// SPDX-License-Identifier: ISC

//! The IANA registries a rule asks membership of, carried as snapshots.
//!
//! **A finding named `_unregistered` is a claim about a registry**, and three
//! entries make it: `media_type_unregistered`, `charset_unregistered` and
//! `auth_scheme_unregistered`. Each was answered by a short list shipped in the
//! rule's configuration instead, so every registered name the list left out was
//! reported as unregistered: `application/pdf`, `text/markdown`, `Shift_JIS`,
//! `windows-1252`, `Negotiate`, `DPoP`. A list short enough to read in a config
//! file cannot be the registry, and the registry is what the entries name.
//!
//! The files beside this one are generated by `just genregistries` and headed
//! with the date IANA gives for each registry's last update. What a deployment
//! knowingly uses beyond them is the rule's `allowed` option, which adds to the
//! registry and never replaces it.

mod auth_schemes;
mod charsets;
mod media_types;

/// Whether a sorted, lowercased snapshot holds `name` under any casing.
///
/// Every name is stored folded to lowercase, because each of the three
/// vocabularies is matched without regard to case.
// cite(RFC 9110 § 8.3.1): "The type and subtype tokens are case-insensitive."
// cite(RFC 9110 § 8.3.2): "In both cases, charset names are matched case-insensitively."
// cite(RFC 9110 § 11.1): "It uses a case-insensitive token to identify the authentication scheme"
fn holds(names: &[&str], name: &str) -> bool {
    names
        .binary_search(&name.to_ascii_lowercase().as_str())
        .is_ok()
}

/// Whether the Media Types registry lists `type_/subtype`.
///
/// The pair is asked, not a string the caller assembled: a registration is a
/// template naming one top-level type and one subtype, and a `+suffix` or a
/// wildcard is neither.
pub fn media_type_registered(type_: &str, subtype: &str) -> bool {
    holds(media_types::NAMES, &format!("{type_}/{subtype}"))
}

/// Whether the Character Sets registry lists `name` as a charset's name, its
/// preferred MIME name, or one of its aliases.
///
/// An alias is a registered name: the registry lists it so that a recipient
/// can recognise it, and `latin1` names ISO-8859-1 as surely as the preferred
/// spelling does.
pub fn charset_registered(name: &str) -> bool {
    holds(charsets::NAMES, name)
}

/// Whether the HTTP Authentication Scheme registry lists `name`.
pub fn auth_scheme_registered(name: &str) -> bool {
    holds(auth_schemes::NAMES, name)
}

#[cfg(test)]
mod tests {
    use super::*;
    use rstest::rstest;

    /// The lookup is a binary search, so a snapshot out of order or holding an
    /// uppercase byte answers "unregistered" for a name it lists. The generator
    /// sorts and folds; this is what holds a hand edit to the same standard.
    #[rstest]
    #[case::media_types(media_types::NAMES)]
    #[case::charsets(charsets::NAMES)]
    #[case::auth_schemes(auth_schemes::NAMES)]
    fn a_snapshot_is_folded_sorted_and_unique(#[case] names: &[&str]) {
        for pair in names.windows(2) {
            assert!(
                pair[0] < pair[1],
                "{:?} is not before {:?}",
                pair[0],
                pair[1]
            );
        }
        for name in names {
            assert_eq!(*name, name.to_ascii_lowercase());
        }
    }

    #[rstest]
    #[case("application", "pdf", true)]
    #[case("text", "markdown", true)]
    #[case("multipart", "mixed", true)]
    #[case("TEXT", "HTML", true)]
    #[case("application", "protobuf", true)]
    #[case("application", "x-protobuf", false)]
    #[case("httpd", "unix-directory", false)]
    #[case("image", "x-icon", false)]
    #[case("application", "+json", false)]
    #[case("*", "*", false)]
    fn media_types_are_the_registrys(
        #[case] type_: &str,
        #[case] subtype: &str,
        #[case] expected: bool,
    ) {
        assert_eq!(media_type_registered(type_, subtype), expected);
    }

    #[rstest]
    #[case("utf-8", true)]
    #[case("UTF-8", true)]
    #[case("Shift_JIS", true)]
    #[case("windows-1252", true)]
    #[case("latin1", true)]
    #[case("utf8", false)]
    #[case("cp1252", false)]
    fn charsets_are_the_registrys(#[case] name: &str, #[case] expected: bool) {
        assert_eq!(charset_registered(name), expected);
    }

    #[rstest]
    #[case("Basic", true)]
    #[case("negotiate", true)]
    #[case("DPoP", true)]
    #[case("SCRAM-SHA-256", true)]
    #[case("X-MyAuth", false)]
    #[case("AidLogin", false)]
    fn auth_schemes_are_the_registrys(#[case] name: &str, #[case] expected: bool) {
        assert_eq!(auth_scheme_registered(name), expected);
    }
}
