// SPDX-FileCopyrightText: 2026 Alexandre Gomes Gaigalas <alganet@gmail.com>
//
// SPDX-License-Identifier: ISC

//! The IANA "HTTP Field Name" registry, as last updated on 2026-08-28.
//!
//! Every field name whose Structured Type column names a `field_type`, one list per type, folded to lowercase and sorted.
//!
//! Generated by `just genregistries` from what IANA publishes below, which
//! is the only way this file should change:
//!
//! - <https://www.iana.org/assignments/http-fields/field-names.csv>

// cite(RFC 9651 § 5): "The "Structured Type" column indicates the type of the field (per RFC 9651), if any, and may be "Dictionary", "List", or "Item"."
pub(super) const ITEMS: &[&str] = &[
    "activate-storage-access",
    "available-dictionary",
    "capsule-protocol",
    "client-cert",
    "concealed-auth-export",
    "connect-udp-bind",
    "cross-origin-embedder-policy",
    "cross-origin-embedder-policy-report-only",
    "cross-origin-opener-policy",
    "cross-origin-opener-policy-report-only",
    "deprecation",
    "dictionary-id",
    "incremental",
    "origin-agent-cluster",
    "sec-fetch-dest",
    "sec-fetch-mode",
    "sec-fetch-site",
    "sec-fetch-user",
];

pub(super) const LISTS: &[&str] = &[
    "accept-ch",
    "accept-query",
    "cache-group-invalidation",
    "cache-groups",
    "cache-status",
    "client-cert-chain",
    "proxy-public-address",
    "proxy-status",
];

pub(super) const DICTIONARIES: &[&str] = &[
    "cdn-cache-control",
    "content-digest",
    "priority",
    "repr-digest",
    "signature",
    "signature-input",
    "unencoded-digest",
    "use-as-dictionary",
    "want-content-digest",
    "want-repr-digest",
    "want-unencoded-digest",
];
