// SPDX-FileCopyrightText: 2025 Alexandre Gomes Gaigalas <alganet@gmail.com>
//
// SPDX-License-Identifier: ISC

use crate::lint::Violation;
use crate::rules::Rule;

pub struct AgeHeaderNumeric;

impl Rule for AgeHeaderNumeric {
    fn id(&self) -> &'static str {
        "age_header_numeric"
    }

    fn scope(&self) -> crate::rules::RuleScope {
        // Age is defined as a response header field, so only responses are inspected.
        // cite(RFC 9111 § 5.1): "The "Age" response header field conveys the sender's estimate of the time since the response was generated or successfully validated at the origin server"
        crate::rules::RuleScope::Server
    }

    fn check_transaction(
        &self,
        tx: &crate::http_transaction::HttpTransaction,
        _history: &crate::transaction_history::TransactionHistory,
        cfg: &crate::config::Config,
    ) -> Option<Violation> {
        let config = crate::rules::parse_rule_config(cfg, self.id()).ok()?;
        // Applies to responses only
        let resp = tx.response.as_ref()?;

        // Age is a singleton, so a well-formed message carries exactly one line. Every
        // line present is still validated rather than only the first: this rule reports
        // what the sender emitted, whereas the SHOULD below governs what a *cache* does
        // when it meets a list-valued Age. The multiplicity itself is not flagged here —
        // no such check exists yet, and adding one would be a behavior change.
        // cite(RFC 9111 § 5.1): "Although it is defined as a singleton header field, a cache encountering a message with a list-based Age field value SHOULD use the first member of the field value, discarding subsequent ones."
        for val in resp.headers.get_all("age").iter() {
            let s = match val.to_str() {
                Ok(s) => s.trim(),
                Err(_) => {
                    return Some(Violation {
                        rule: self.id().into(),
                        severity: config.severity,
                        message: "Age header contains non-UTF8 value".into(),
                    })
                }
            };

            // Age must be a non-negative integer (delta-seconds). Match the grammar
            // directly rather than via an integer parse: `u64::from_str` accepts a
            // leading "+", which `1*DIGIT` does not, and it rejects values too large
            // for u64, which the grammar does allow. The `Age = delta-seconds` ABNF is
            // too short to quote on its own, so the sentence below carries the shape;
            // the clamp requirement is why an over-long run of digits is accepted here
            // rather than reported as malformed.
            // cite(RFC 9111 § 5.1): "The Age field value is a non-negative integer, representing time in seconds"
            // cite(RFC 9111 § 1.2.2): "If a cache receives a delta-seconds value greater than the greatest integer it can represent, or if any of its subsequent calculations overflows, the cache MUST consider the value to be 2147483648 (2^31) or the greatest positive integer it can conveniently represent."
            if !s.is_empty() && s.bytes().all(|b| b.is_ascii_digit()) {
                continue;
            }

            return Some(Violation {
                rule: self.id().into(),
                severity: config.severity,
                message: format!(
                    "Age value '{}' is invalid: must be a non-negative integer (delta-seconds)",
                    s
                ),
            });
        }

        None
    }

    fn title(&self) -> Option<&'static str> {
        Some("Age Header Numeric")
    }

    fn description(&self) -> &'static str {
        "The `Age` header, when present in a response, indicates the time (in seconds) since the response was generated by an origin server. This rule ensures the `Age` header value is a non-negative integer (`delta-seconds`) as required by the HTTP specifications."
    }

    fn specifications(&self) -> &'static [crate::rules::SpecRef] {
        &[crate::rules::SpecRef {
            spec: "RFC 9111",
            section: Some("5.1"),
            url: "https://www.rfc-editor.org/rfc/rfc9111.html#section-5.1",
            note: "`Age` field-value: delta-seconds (non-negative integer)",
        }]
    }

    fn examples(&self) -> &'static [crate::rules::Example] {
        use crate::rules::{Compliance, Example};
        &[
            Example {
                compliance: Compliance::Compliant,
                label: None,
                snippet: "HTTP/1.1 200 OK\nAge: 120",
            },
            Example {
                compliance: Compliance::NonCompliant,
                label: None,
                snippet: "HTTP/1.1 200 OK\nAge: -1",
            },
            Example {
                compliance: Compliance::NonCompliant,
                label: None,
                snippet: "HTTP/1.1 200 OK\nAge: abc",
            },
        ]
    }
}

/// Registers this rule into the engine's auto-collected catalogue.
#[linkme::distributed_slice(crate::rules::REGISTERED_RULES)]
static REGISTRATION: &dyn crate::rules::Rule = &AgeHeaderNumeric;

#[cfg(test)]
mod tests {
    use super::*;
    use rstest::rstest;

    #[rstest]
    #[case(200, &[("age", "120")], false)]
    #[case(200, &[("age", "0")], false)]
    #[case(200, &[("age", "-1")], true)]
    #[case(200, &[("age", "abc")], true)]
    #[case(200, &[("age", "+120")], true)]
    #[case(200, &[("age", "")], true)]
    #[case(200, &[("age", "99999999999999999999999")], false)]
    fn check_cases(
        #[case] status: u16,
        #[case] hdrs: &[(&str, &str)],
        #[case] expect_violation: bool,
    ) -> anyhow::Result<()> {
        let rule = AgeHeaderNumeric;
        let tx = crate::test_helpers::make_test_transaction_with_response(status, hdrs);
        let v = crate::test_helpers::run_rule(
            &rule,
            &tx,
            &crate::transaction_history::TransactionHistory::empty(),
            &crate::test_helpers::make_test_config_with_enabled_rules(&[rule.id()]),
        );

        if expect_violation {
            assert!(v.is_some(), "expected violation for headers: {:?}", hdrs);
        } else {
            assert!(
                v.is_none(),
                "did not expect violation for headers: {:?}",
                hdrs
            );
        }
        Ok(())
    }

    #[test]
    fn comma_separated_values_are_invalid() -> anyhow::Result<()> {
        let rule = AgeHeaderNumeric;
        let tx =
            crate::test_helpers::make_test_transaction_with_response(200, &[("age", "120, 240")]);
        let v = crate::test_helpers::run_rule(
            &rule,
            &tx,
            &crate::transaction_history::TransactionHistory::empty(),
            &crate::test_helpers::make_test_config_with_enabled_rules(&[rule.id()]),
        );
        assert!(v.is_some());
        Ok(())
    }

    #[test]
    fn non_utf8_header_value_is_violation() -> anyhow::Result<()> {
        use hyper::header::HeaderValue;
        use hyper::HeaderMap;
        let rule = AgeHeaderNumeric;
        let mut tx = crate::test_helpers::make_test_transaction();
        let mut hm = HeaderMap::new();
        // create non-utf8 header value
        let bad = HeaderValue::from_bytes(&[0xff]).expect("should construct non-utf8 header");
        hm.insert("age", bad);
        tx.response = Some(crate::http_transaction::ResponseInfo {
            status: 200,
            version: "HTTP/1.1".into(),
            headers: hm,

            body_length: None,
            trailers: None,
        });

        let v = crate::test_helpers::run_rule(
            &rule,
            &tx,
            &crate::transaction_history::TransactionHistory::empty(),
            &crate::test_helpers::make_test_config_with_enabled_rules(&[rule.id()]),
        );
        assert!(v.is_some());
        let msg = v.unwrap().message;
        assert!(msg.contains("non-UTF8") || msg.contains("invalid"));
        Ok(())
    }

    #[test]
    fn no_response_no_violation() -> anyhow::Result<()> {
        let rule = AgeHeaderNumeric;
        let tx = crate::test_helpers::make_test_transaction();
        let v = crate::test_helpers::run_rule(
            &rule,
            &tx,
            &crate::transaction_history::TransactionHistory::empty(),
            &crate::test_helpers::make_test_config_with_enabled_rules(&[rule.id()]),
        );
        assert!(v.is_none());
        Ok(())
    }

    #[test]
    fn scope_is_server() {
        let rule = AgeHeaderNumeric;
        assert_eq!(rule.scope(), crate::rules::RuleScope::Server);
    }

    #[test]
    fn violation_message_meaningful() -> anyhow::Result<()> {
        let rule = AgeHeaderNumeric;
        let tx = crate::test_helpers::make_test_transaction_with_response(200, &[("age", "bad")]);
        let v = crate::test_helpers::run_rule(
            &rule,
            &tx,
            &crate::transaction_history::TransactionHistory::empty(),
            &crate::test_helpers::make_test_config_with_enabled_rules(&[rule.id()]),
        );
        assert!(v.is_some());
        let msg = v.unwrap().message;
        assert!(msg.contains("invalid"));
        Ok(())
    }
}
