// SPDX-FileCopyrightText: 2025 Alexandre Gomes Gaigalas <alganet@gmail.com>
//
// SPDX-License-Identifier: ISC

use crate::lint::Violation;
use crate::rules::{Rule, RuleMeta};
use crate::violations::delta_seconds::{
    DELTA_SECONDS_CHARACTER_FORBIDDEN, DELTA_SECONDS_EMPTY, RFC_9111_1_2_2,
};
use crate::violations::ViolationDef;

pub struct AgeHeaderNumeric;

/// Both of them are the production's, and there is nothing of `Age`'s own left
/// to report.
///
/// `Age = delta-seconds` is the whole grammar — the field adds no punctuation,
/// no list, no parameter — so every syntactic thing this rule can say is a
/// statement about `1*DIGIT` and none of it is about the field. What stays the
/// rule's is which message it reads and what the value *means* there, which is
/// what the § 5.1 citations below carry.
static DECLARED: &[&ViolationDef] = &[&DELTA_SECONDS_EMPTY, &DELTA_SECONDS_CHARACTER_FORBIDDEN];

/// The specification references this rule declares, each named so a finding
/// site can cite the one it enforces. `specifications()` below is built from
/// exactly these, so the docs and the citations cannot name different text.
const RFC_9111_5_1: crate::rules::SpecRef = crate::rules::SpecRef {
    spec: "RFC 9111",
    section: Some("5.1"),
    url: "https://www.rfc-editor.org/rfc/rfc9111.html#section-5.1",
    note: "`Age` field-value: delta-seconds (non-negative integer)",
};

impl RuleMeta for AgeHeaderNumeric {
    fn id(&self) -> &'static str {
        "age_header_numeric"
    }

    fn config_example(&self) -> &'static str {
        r#"enabled = true
severity = "warn"
"#
    }

    fn title(&self) -> Option<&'static str> {
        Some("Age Header Numeric")
    }

    fn description(&self) -> &'static str {
        "The `Age` header, when present in a response, indicates the time (in seconds) since the response was generated by an origin server. This rule ensures the `Age` header value is a non-negative integer (`delta-seconds`) as required by the HTTP specifications.\n\nThe value is read as the octets the sender wrote, so an octet outside US-ASCII is reported as the character `DIGIT` does not admit rather than as a verdict about the value's encoding — `delta-seconds` is ten visible US-ASCII characters, so there was never anything for the encoding to say first. A run of digits too long for any integer type is *not* reported: RFC 9111 §1.2.2 tells a cache to clamp such a value, which makes it conforming."
    }

    fn specifications(&self) -> &'static [crate::rules::SpecRef] {
        &[RFC_9111_5_1, RFC_9111_1_2_2]
    }

    fn violations(&self) -> &'static [&'static ViolationDef] {
        DECLARED
    }

    fn examples(&self) -> &'static [crate::rules::Example] {
        use crate::rules::{Compliance, Example};
        &[
            Example {
                compliance: Compliance::Compliant,
                label: None,
                snippet: "HTTP/1.1 200 OK\nAge: 120",
            },
            Example {
                compliance: Compliance::NonCompliant,
                label: None,
                snippet: "HTTP/1.1 200 OK\nAge: -1",
            },
            Example {
                compliance: Compliance::NonCompliant,
                label: None,
                snippet: "HTTP/1.1 200 OK\nAge: abc",
            },
        ]
    }
}

impl Rule for AgeHeaderNumeric {
    fn scope(&self) -> crate::rules::RuleScope {
        // Age is defined as a response header field, so only responses are inspected.
        // cite(RFC 9111 § 5.1): "The "Age" response header field conveys the sender's estimate of the time since the response was generated or successfully validated at the origin server"
        crate::rules::RuleScope::Server
    }

    fn findings(
        &self,
        tx: &crate::http_transaction::HttpTransaction,
        _history: &crate::transaction_history::TransactionHistory,
        ctx: &crate::rules::RuleContext<'_>,
    ) -> Vec<Violation> {
        // Single-finding body behind an Option: `?` ends it early, and the
        // one finding (or none) becomes the vector.
        let finding =
            || -> Option<Violation> {
                // Applies to responses only
                let resp = tx.response.as_ref()?;

                // Age is a singleton, so a well-formed message carries exactly one line. Every
                // line present is still validated rather than only the first: this rule reports
                // what the sender emitted, whereas the SHOULD below governs what a *cache* does
                // when it meets a list-valued Age. The multiplicity itself is not flagged here —
                // no such check exists yet, and adding one would be a behavior change.
                // cite(RFC 9111 § 5.1): "Although it is defined as a singleton header field, a cache encountering a message with a list-based Age field value SHOULD use the first member of the field value, discarding subsequent ones."
                for val in resp.headers.get_all("age").iter() {
                    // One `char` per octet, and `OWS` rather than `str::trim`: the
                    // whole production is ten visible US-ASCII characters, so an
                    // octet above it is a character `DIGIT` does not admit and not a
                    // fact about the field's encoding — and %xA0, which `str::trim`
                    // removes, is one of those octets rather than space around the
                    // value.
                    let line = crate::helpers::headers::field_line_as_written(val);
                    let s = crate::helpers::headers::trim_ows(&line);

                    // Age must be a non-negative integer (delta-seconds). Match the grammar
                    // directly rather than via an integer parse: `u64::from_str` accepts a
                    // leading "+", which `1*DIGIT` does not, and it rejects values too large
                    // for u64, which the grammar does allow. The sentence below is what makes
                    // this field's value that production; the production itself, and the clamp
                    // that is why an over-long run of digits is accepted here rather than
                    // reported as malformed, are on the defects.
                    // cite(RFC 9111 § 5.1): "The Age field value is a non-negative integer, representing time in seconds"
                    if s.is_empty() {
                        return Some(ctx.report_with(
                        &DELTA_SECONDS_EMPTY,
                        "Age states no time: `delta-seconds` is `1*DIGIT` and this value has \
                         no digits"
                            .into(),
                    ));
                    }

                    if let Some(c) = s.chars().find(|c| !c.is_ascii_digit()) {
                        return Some(ctx.report_with(
                            &DELTA_SECONDS_CHARACTER_FORBIDDEN,
                            format!(
                                "Age value '{}' is invalid: {} is no `DIGIT`, so the value is not \
                             the `delta-seconds` the field is",
                                crate::helpers::shown::shown_in_finding(s),
                                crate::helpers::shown::describe_char(c),
                            ),
                        ));
                    }
                }

                None
            };
        Vec::from_iter(finding())
    }
}

/// Registers this rule into the engine's auto-collected catalogue.
#[linkme::distributed_slice(crate::rules::REGISTERED_RULES)]
static REGISTRATION: &dyn crate::rules::Rule = &AgeHeaderNumeric;

#[cfg(test)]
mod tests {
    use super::*;
    use rstest::rstest;

    #[rstest]
    #[case(200, &[("age", "120")], false)]
    #[case(200, &[("age", "0")], false)]
    #[case(200, &[("age", "-1")], true)]
    #[case(200, &[("age", "abc")], true)]
    #[case(200, &[("age", "+120")], true)]
    #[case(200, &[("age", "")], true)]
    #[case(200, &[("age", "99999999999999999999999")], false)]
    fn check_cases(
        #[case] status: u16,
        #[case] hdrs: &[(&str, &str)],
        #[case] expect_violation: bool,
    ) -> anyhow::Result<()> {
        let rule = AgeHeaderNumeric;
        let tx = crate::test_helpers::make_test_transaction_with_response(status, hdrs);
        let v = crate::test_helpers::run_rule(
            &rule,
            &tx,
            &crate::transaction_history::TransactionHistory::empty(),
            &crate::test_helpers::make_test_config_with_enabled_rules(&[rule.id()]),
        );

        if expect_violation {
            assert!(v.is_some(), "expected violation for headers: {:?}", hdrs);
        } else {
            assert!(
                v.is_none(),
                "did not expect violation for headers: {:?}",
                hdrs
            );
        }
        Ok(())
    }

    #[test]
    fn comma_separated_values_are_invalid() -> anyhow::Result<()> {
        let rule = AgeHeaderNumeric;
        let tx =
            crate::test_helpers::make_test_transaction_with_response(200, &[("age", "120, 240")]);
        let v = crate::test_helpers::run_rule(
            &rule,
            &tx,
            &crate::transaction_history::TransactionHistory::empty(),
            &crate::test_helpers::make_test_config_with_enabled_rules(&[rule.id()]),
        );
        assert!(v.is_some());
        Ok(())
    }

    /// The octet is named by the production that refuses it. It used to be a
    /// verdict about the value's encoding, which could not say which octet
    /// arrived — and `DIGIT` had already refused it, because `delta-seconds` is
    /// ten visible US-ASCII characters and nothing else.
    #[test]
    fn an_octet_outside_us_ascii_is_named_rather_than_called_an_encoding() -> anyhow::Result<()> {
        use hyper::header::HeaderValue;
        use hyper::HeaderMap;
        let rule = AgeHeaderNumeric;
        let mut tx = crate::test_helpers::make_test_transaction();
        let mut hm = HeaderMap::new();
        let bad = HeaderValue::from_bytes(&[0xff]).expect("should construct non-utf8 header");
        hm.insert("age", bad);
        tx.response = Some(crate::http_transaction::ResponseInfo {
            status: 200,
            version: "HTTP/1.1".into(),
            headers: hm,

            body_length: None,
            trailers: None,
        });

        let v = crate::test_helpers::run_rule(
            &rule,
            &tx,
            &crate::transaction_history::TransactionHistory::empty(),
            &crate::test_helpers::make_test_config_with_enabled_rules(&[rule.id()]),
        )
        .expect("a finding");
        assert_eq!(v.violation, "delta_seconds_character_forbidden");
        assert!(v.message.contains("0xFF"), "{}", v.message);
        Ok(())
    }

    /// %xA0 is `obs-text` a sender wrote *inside* the value, and `str::trim`
    /// removed it — leaving `120` and no finding. `OWS` is `*( SP / HTAB )`,
    /// so the octet survives to reach the alphabet that refuses it.
    #[test]
    fn the_obs_text_that_looks_like_space_is_measured_rather_than_trimmed() -> anyhow::Result<()> {
        use hyper::header::HeaderValue;
        use hyper::HeaderMap;
        let mut tx = crate::test_helpers::make_test_transaction();
        let mut hm = HeaderMap::new();
        hm.insert("age", HeaderValue::from_bytes(&[0xA0, b'1', b'2', b'0'])?);
        tx.response = Some(crate::http_transaction::ResponseInfo {
            status: 200,
            version: "HTTP/1.1".into(),
            headers: hm,
            body_length: None,
            trailers: None,
        });

        let v = crate::test_helpers::run_rule(
            &AgeHeaderNumeric,
            &tx,
            &crate::transaction_history::TransactionHistory::empty(),
            &crate::test_helpers::make_test_config_with_enabled_rules(&["age_header_numeric"]),
        )
        .expect("a finding");
        assert_eq!(v.violation, "delta_seconds_character_forbidden");
        assert!(v.message.contains("0xA0"), "{}", v.message);
        Ok(())
    }

    /// Both halves of `1*DIGIT` report, and both report as the production
    /// rather than as the field: `Age = delta-seconds` is the whole grammar, so
    /// there is no `age_…` id for either of them to have been.
    #[test]
    fn each_defect_is_the_productions_and_not_the_fields() {
        for (value, id) in [
            ("", "delta_seconds_empty"),
            ("-1", "delta_seconds_character_forbidden"),
            ("+120", "delta_seconds_character_forbidden"),
            ("120, 240", "delta_seconds_character_forbidden"),
        ] {
            let tx =
                crate::test_helpers::make_test_transaction_with_response(200, &[("age", value)]);
            let found = crate::test_helpers::run_rule(
                &AgeHeaderNumeric,
                &tx,
                &crate::transaction_history::TransactionHistory::empty(),
                &crate::test_helpers::make_test_config_with_enabled_rules(&["age_header_numeric"]),
            )
            .unwrap_or_else(|| panic!("{value:?}"));
            assert_eq!(found.violation, id, "{value:?}");
        }
    }

    #[test]
    fn no_response_no_violation() -> anyhow::Result<()> {
        let rule = AgeHeaderNumeric;
        let tx = crate::test_helpers::make_test_transaction();
        let v = crate::test_helpers::run_rule(
            &rule,
            &tx,
            &crate::transaction_history::TransactionHistory::empty(),
            &crate::test_helpers::make_test_config_with_enabled_rules(&[rule.id()]),
        );
        assert!(v.is_none());
        Ok(())
    }

    #[test]
    fn scope_is_server() {
        let rule = AgeHeaderNumeric;
        assert_eq!(rule.scope(), crate::rules::RuleScope::Server);
    }

    #[test]
    fn violation_message_meaningful() -> anyhow::Result<()> {
        let rule = AgeHeaderNumeric;
        let tx = crate::test_helpers::make_test_transaction_with_response(200, &[("age", "bad")]);
        let v = crate::test_helpers::run_rule(
            &rule,
            &tx,
            &crate::transaction_history::TransactionHistory::empty(),
            &crate::test_helpers::make_test_config_with_enabled_rules(&[rule.id()]),
        );
        assert!(v.is_some());
        let msg = v.unwrap().message;
        assert!(msg.contains("invalid"));
        Ok(())
    }
}
