// SPDX-FileCopyrightText: 2026 Alexandre Gomes Gaigalas <alganet@gmail.com>
//
// SPDX-License-Identifier: ISC

use crate::lint::Violation;
use crate::rules::Rule;

/// `If-Unmodified-Since` (RFC 9110 §13.1.4) is defined as an HTTP-date; a sender must
/// generate it as an IMF-fixdate (§5.6.7). This checks the sender's obligation.
pub struct MessageIfUnmodifiedSinceDateFormat;

impl Rule for MessageIfUnmodifiedSinceDateFormat {
    fn id(&self) -> &'static str {
        "message_if_unmodified_since_date_format"
    }

    fn scope(&self) -> crate::rules::RuleScope {
        crate::rules::RuleScope::Both
    }

    fn check_transaction(
        &self,
        tx: &crate::http_transaction::HttpTransaction,
        _history: &crate::transaction_history::TransactionHistory,
        cfg: &crate::config::Config,
    ) -> Option<Violation> {
        let config = crate::rules::parse_rule_config(cfg, self.id()).ok()?;
        // Applies to requests only
        for hv in tx.request.headers.get_all("if-unmodified-since").iter() {
            let s = match hv.to_str() {
                Ok(s) => s,
                Err(_) => {
                    return Some(Violation {
                        rule: self.id().into(),
                        severity: config.severity,
                        message: "If-Unmodified-Since header contains non-UTF8 value".into(),
                    })
                }
            };

            if s.trim().is_empty() {
                return Some(Violation {
                    rule: self.id().into(),
                    severity: config.severity,
                    message: "If-Unmodified-Since header is empty or contains only whitespace"
                        .into(),
                });
            }

            // The field is defined as HTTP-date, which is the grammar; it is not the
            // licence. A request is generated by a sender, and a sender is confined to
            // IMF-fixdate, so the obsolete two are violations here even though we are
            // obliged to parse them.
            // cite(RFC 9110 § 13.1.4): "If-Unmodified-Since = HTTP-date"
            // cite(RFC 9110 § 5.6.7): "When a sender generates a field that contains one or more timestamps defined as HTTP-date, the sender MUST generate those timestamps in the IMF-fixdate format."
            if !crate::http_date::is_valid_imf_fixdate(s.trim()) {
                return Some(Violation {
                    rule: self.id().into(),
                    severity: config.severity,
                    message:
                        "If-Unmodified-Since header is not a valid IMF-fixdate (RFC 9110 §5.6.7)"
                            .into(),
                });
            }
        }

        None
    }

    fn title(&self) -> Option<&'static str> {
        Some("Message If-Unmodified-Since Date Format")
    }

    fn description(&self) -> &'static str {
        "The `If-Unmodified-Since` request header is defined as an HTTP-date, and a sender MUST generate it in the IMF-fixdate format. This rule flags values that are not a valid IMF-fixdate — including the two obsolete formats, which a recipient must still accept but no sender may emit — or that contain non-UTF8 bytes."
    }

    fn specifications(&self) -> &'static [crate::rules::SpecRef] {
        &[crate::rules::SpecRef {
            spec: "RFC 9110",
            section: Some("13.1.4"),
            url: "https://www.rfc-editor.org/rfc/rfc9110.html#section-13.1.4",
            note: "If-Unmodified-Since header",
        }]
    }

    fn examples(&self) -> &'static [crate::rules::Example] {
        use crate::rules::{Compliance, Example};
        &[
            Example {
                compliance: Compliance::Compliant,
                label: None,
                snippet:
                    "GET /resource HTTP/1.1\nIf-Unmodified-Since: Wed, 21 Oct 2015 07:28:00 GMT",
            },
            Example {
                compliance: Compliance::NonCompliant,
                label: None,
                snippet: "GET /resource HTTP/1.1\nIf-Unmodified-Since: not-a-date",
            },
            Example {
                compliance: Compliance::NonCompliant,
                label: None,
                snippet: "GET /resource HTTP/1.1\nIf-Unmodified-Since: \\xff",
            },
        ]
    }
}

/// Registers this rule into the engine's auto-collected catalogue.
#[linkme::distributed_slice(crate::rules::REGISTERED_RULES)]
static REGISTRATION: &dyn crate::rules::Rule = &MessageIfUnmodifiedSinceDateFormat;

#[cfg(test)]
mod tests {
    use super::*;
    use rstest::rstest;

    #[rstest]
    #[case(Some("Wed, 21 Oct 2015 07:28:00 GMT"), false)]
    #[case(Some("not-a-date"), true)]
    // RFC 9110 § 5.6.7's own examples of the two obsolete formats. A recipient must
    // accept both; a sender may generate neither, and a request is sent by a sender.
    #[case(Some("Sunday, 06-Nov-94 08:49:37 GMT"), true)]
    #[case(Some("Sun Nov  6 08:49:37 1994"), true)]
    #[case(None, false)]
    fn if_unmodified_since_cases(
        #[case] header: Option<&str>,
        #[case] expect_violation: bool,
    ) -> anyhow::Result<()> {
        let rule = MessageIfUnmodifiedSinceDateFormat;
        let mut tx = crate::test_helpers::make_test_transaction();
        if let Some(h) = header {
            tx.request.headers =
                crate::test_helpers::make_headers_from_pairs(&[("if-unmodified-since", h)]);
        }

        let v = rule.check_transaction(
            &tx,
            &crate::transaction_history::TransactionHistory::empty(),
            &crate::test_helpers::make_test_config_with_enabled_rules(&[rule.id()]),
        );
        if expect_violation {
            assert!(v.is_some());
        } else {
            assert!(v.is_none());
        }
        Ok(())
    }

    #[test]
    fn non_utf8_header_value_is_violation() -> anyhow::Result<()> {
        use hyper::header::HeaderValue;
        use hyper::HeaderMap;
        let rule = MessageIfUnmodifiedSinceDateFormat;

        let mut tx = crate::test_helpers::make_test_transaction();
        let mut hm = HeaderMap::new();
        let bad = HeaderValue::from_bytes(&[0xff]).expect("should construct non-utf8 header");
        hm.insert("if-unmodified-since", bad);
        tx.request.headers = hm;

        let v = rule.check_transaction(
            &tx,
            &crate::transaction_history::TransactionHistory::empty(),
            &crate::test_helpers::make_test_config_with_enabled_rules(&[rule.id()]),
        );
        assert!(v.is_some());
        Ok(())
    }

    #[test]
    fn empty_header_value_reports_violation() {
        let rule = MessageIfUnmodifiedSinceDateFormat;
        let mut tx = crate::test_helpers::make_test_transaction();
        tx.request.headers =
            crate::test_helpers::make_headers_from_pairs(&[("if-unmodified-since", "")]);

        let v = rule.check_transaction(
            &tx,
            &crate::transaction_history::TransactionHistory::empty(),
            &crate::test_helpers::make_test_config_with_enabled_rules(&[rule.id()]),
        );
        assert!(v.is_some());
        let msg = v.unwrap().message;
        assert!(msg.contains("empty or contains only whitespace"));
    }

    #[test]
    fn multiple_header_fields_one_invalid_reports_violation() -> anyhow::Result<()> {
        use hyper::header::HeaderValue;
        use hyper::HeaderMap;
        let rule = MessageIfUnmodifiedSinceDateFormat;

        let mut tx = crate::test_helpers::make_test_transaction();
        let mut hm = HeaderMap::new();
        hm.append(
            "if-unmodified-since",
            HeaderValue::from_static("Wed, 21 Oct 2015 07:28:00 GMT"),
        );
        hm.append(
            "if-unmodified-since",
            HeaderValue::from_static("not-a-date"),
        );
        tx.request.headers = hm;

        let v = rule.check_transaction(
            &tx,
            &crate::transaction_history::TransactionHistory::empty(),
            &crate::test_helpers::make_test_config_with_enabled_rules(&[rule.id()]),
        );
        assert!(v.is_some());
        Ok(())
    }

    #[test]
    fn multiple_header_fields_merged_and_valid() -> anyhow::Result<()> {
        use hyper::header::HeaderValue;
        use hyper::HeaderMap;
        let rule = MessageIfUnmodifiedSinceDateFormat;

        let mut tx = crate::test_helpers::make_test_transaction();
        let mut hm = HeaderMap::new();
        hm.append(
            "if-unmodified-since",
            HeaderValue::from_static("Wed, 21 Oct 2015 07:28:00 GMT"),
        );
        hm.append(
            "if-unmodified-since",
            HeaderValue::from_static("Wed, 02 Jan 2030 12:00:00 GMT"),
        );
        tx.request.headers = hm;

        let v = rule.check_transaction(
            &tx,
            &crate::transaction_history::TransactionHistory::empty(),
            &crate::test_helpers::make_test_config_with_enabled_rules(&[rule.id()]),
        );
        // Using multiple valid headers is acceptable (validate each); no violation expected if all valid
        assert!(v.is_none());
        Ok(())
    }

    #[test]
    fn validate_rules_with_valid_config() -> anyhow::Result<()> {
        let mut cfg = crate::config::Config::default();
        crate::test_helpers::enable_rule(&mut cfg, "message_if_unmodified_since_date_format");
        crate::rules::validate_rules(&cfg)?;
        Ok(())
    }

    #[test]
    fn id_and_scope_are_expected() {
        let r = MessageIfUnmodifiedSinceDateFormat;
        assert_eq!(r.id(), "message_if_unmodified_since_date_format");
        assert_eq!(r.scope(), crate::rules::RuleScope::Both);
    }
}
