// SPDX-FileCopyrightText: 2026 Alexandre Gomes Gaigalas <alganet@gmail.com>
//
// SPDX-License-Identifier: ISC

use crate::lint::Violation;
use crate::rules::{Rule, RuleMeta};

/// Ensure OAuth 2.0 authorization code flows correlate the `state` parameter
/// between the initial authorization request and the subsequent callback.
///
/// The `state` parameter is an opaque value generated by the client and
/// included in the authorization request (with `response_type=code`).  RFC 6749
/// §4.1.1 RECOMMENDS (SHOULD) that clients use `state`, and requires the
/// authorization server to echo the same `state` value back only if it was
/// present in the request.  This rule treats `state` as required for code flows
/// to help prevent CSRF and replay attacks.
///
/// The rule watches outgoing requests.  It records any `state` values seen in
/// authorization requests and, when a later request includes an OAuth `code`,
/// verifies a matching `state` was observed earlier.  Missing or mismatched
/// `state` parameters trigger violations.
///
/// Correlation is performed only within the transaction history provided by
/// the engine for this rule. In the current engine this typically includes
/// requests to the same resource/origin as the one being checked; requests to
/// other origins (for example, an IdP on a different host) may not be
/// available for correlation, depending on query configuration.
pub struct Oauth2CodeFlow;

/// The specification references this rule declares, each named so a finding
/// site can cite the one it enforces. `specifications()` below is built from
/// exactly these, so the docs and the citations cannot name different text.
use crate::violations::oauth2::{
    OAUTH2_CALLBACK_STATE_MISSING, OAUTH2_REQUEST_STATE_MISSING, OAUTH2_STATE_CONFLICTING,
    RFC_6749_10_12, RFC_6749_4_1_1, RFC_6749_4_1_2,
};
use crate::violations::ViolationDef;

/// Three, and they are the two ends of one flow plus the join between them:
/// a request that started without a binding, a callback that arrived without
/// one, and a callback whose binding matches nothing that was sent.
static DECLARED: &[&ViolationDef] = &[
    &OAUTH2_REQUEST_STATE_MISSING,
    &OAUTH2_CALLBACK_STATE_MISSING,
    &OAUTH2_STATE_CONFLICTING,
];

impl RuleMeta for Oauth2CodeFlow {
    fn id(&self) -> &'static str {
        "oauth2_code_flow"
    }

    fn config_example(&self) -> &'static str {
        r#"enabled = true
"#
    }

    fn title(&self) -> Option<&'static str> {
        Some("Stateful OAuth2 Authorization Code Flow")
    }

    fn description(&self) -> &'static str {
        "The OAuth 2.0 authorization code flow **recommends** (SHOULD) that clients generate and include a `state` parameter in the initial authorization request to bind the request and eventual callback.  When the server echoes an authorization `code`, it is required to return the same `state` value **only if** the request contained one (RFC 6749 §4.1.1).  The parameter is optional in the spec, but omitting it leaves the flow vulnerable to CSRF/replay attacks.\n\nThis rule therefore treats a request or callback that either lacks a `state` parameter or provides an empty/whitespace value as a violation, enforcing a best‑practice requirement that a meaningful state be correlated.\n\nThis value prevents cross-site request forgery (CSRF) and replay attacks by ensuring the callback corresponds to a request the client actually initiated. Without this correlation, a malicious site could trick the user agent into sending a `code` it did not request, allowing the attacker to hijack the authorization grant.\n\nThe lint rule observes outgoing requests from a user agent.  It records any `state` seen in authorization requests and, when a later request carries an authorization `code`, verifies that a matching `state` occurred previously. Violations are raised for missing `state` parameters in either direction or when the callback contains a value not previously observed.\n\nThe check does not assume the authorization request and callback share a common origin; the redirect is typically to the client's own domain while the initial request targets the identity provider."
    }

    fn specifications(&self) -> &'static [crate::rules::SpecRef] {
        &[RFC_6749_4_1_1, RFC_6749_4_1_2, RFC_6749_10_12]
    }

    fn violations(&self) -> &'static [&'static ViolationDef] {
        DECLARED
    }

    /// Only examines outgoing requests; does not depend on server behaviour.
    fn party(&self) -> crate::rules::RuleParty {
        crate::rules::RuleParty::Presumed(crate::lint::Party::Client)
    }

    fn examples(&self) -> &'static [crate::rules::Example] {
        use crate::rules::{Compliance, Example};
        &[
            Example {
                compliance: Compliance::Compliant,
                label: None,
                snippet: "> GET /authorize?response_type=code&client_id=1&state=xyz HTTP/1.1\n> Host: idp.example.com\n\n< HTTP/1.1 302 Found\n< Location: https://app.example.com/callback?code=abc&state=xyz",
            },
            Example {
                compliance: Compliance::NonCompliant,
                label: Some("— request missing or empty state"),
                snippet: "> GET /authorize?response_type=code&client_id=1 HTTP/1.1\n> Host: idp.example.com",
            },
            Example {
                compliance: Compliance::NonCompliant,
                label: Some("— callback missing or empty state"),
                snippet: "> GET /callback?code=abc HTTP/1.1\n> Host: app.example.com",
            },
            Example {
                compliance: Compliance::NonCompliant,
                label: Some("— unmatched state"),
                snippet: "> GET /callback?code=abc&state=wrong HTTP/1.1\n> Host: app.example.com",
            },
        ]
    }
}

impl Rule for Oauth2CodeFlow {
    fn findings(
        &self,
        tx: &crate::http_transaction::HttpTransaction,
        history: &crate::transaction_history::TransactionHistory,
        ctx: &crate::rules::RuleContext<'_>,
    ) -> Vec<Violation> {
        // Single-finding body behind an Option: `?` ends it early, and the
        // one finding (or none) becomes the vector.
        let finding = || -> Option<Violation> {
            let req_uri = &tx.request.uri;
            // simple query extraction: portion after '?' if present, ignoring any
            // URI fragment (`#...`) which is not part of the query string.
            let query = req_uri.split_once('?').map(|x| x.1).unwrap_or("");
            let query = query.split('#').next().unwrap_or(query);

            let params = parse_query_string(query);

            // helper to lookup a parameter by name (first occurrence)
            fn get_param<'a>(pairs: &'a [(String, String)], key: &str) -> Option<&'a String> {
                for (k, v) in pairs {
                    if k == key {
                        return Some(v);
                    }
                }
                None
            }

            // An authorization request for the code flow is identified by response_type=code.
            // cite(RFC 6749 § 4.1.1): "REQUIRED.  Value MUST be set to "code"."
            if let Some(rt) = get_param(&params, "response_type") {
                if rt == "code" {
                    // State must be present; empty/whitespace counts as missing. §4.1.1 only
                    // RECOMMENDS the state parameter, but §10.12 makes CSRF protection on the
                    // redirection URI a MUST and names state as the SHOULD mechanism for it — so
                    // requiring state is enforcing that MUST through its recommended vehicle, not
                    // merely being stricter than the parameter's own RECOMMENDED status.
                    // cite(RFC 6749 § 4.1.1): "RECOMMENDED.  An opaque value used by the client to maintain state between the request and callback."
                    // cite(RFC 6749 § 10.12): "The client MUST implement CSRF protection for its redirection URI."
                    // cite(RFC 6749 § 10.12): "The client SHOULD utilize the "state" request parameter to deliver this value"
                    match get_param(&params, "state") {
                        Some(s) if !s.trim().is_empty() => {
                            // OK
                        }
                        _ => {
                            return Some(ctx.report_with(&OAUTH2_REQUEST_STATE_MISSING, "OAuth2 authorization request with response_type=code missing or empty state parameter".into()));
                        }
                    }
                    // nothing else to check for the request itself
                }
            }

            // A callback is identified by the authorization code it carries.
            // cite(RFC 6749 § 4.1.2): "REQUIRED.  The authorization code generated by the authorization server."
            if get_param(&params, "code").is_some() {
                // The callback MUST echo the exact state from the request that started the
                // flow; the correlation below re-derives that request from history and checks
                // the values match, which is the CSRF binding §10.12 requires.
                // cite(RFC 6749 § 4.1.2): "REQUIRED if the "state" parameter was present in the client authorization request.  The exact value received from the client."
                match get_param(&params, "state") {
                    Some(state_val) if !state_val.trim().is_empty() => {
                        // look for prior authorization request with same state
                        let mut seen = false;
                        for prev in history.iter() {
                            let prev_q =
                                prev.request.uri.split_once('?').map(|x| x.1).unwrap_or("");
                            let prev_q = prev_q.split('#').next().unwrap_or(prev_q);
                            let prev_params = parse_query_string(prev_q);
                            if let Some(rt2) = get_param(&prev_params, "response_type") {
                                if rt2 == "code" {
                                    if let Some(ps) = get_param(&prev_params, "state") {
                                        if ps == state_val {
                                            seen = true;
                                            break;
                                        }
                                    }
                                }
                            }
                        }
                        if !seen {
                            return Some(ctx.report_with(&OAUTH2_STATE_CONFLICTING, "OAuth2 authorization callback used a state value that was not seen in a prior request".into()));
                        }
                    }
                    _ => {
                        return Some(ctx.report_with(
                            &OAUTH2_CALLBACK_STATE_MISSING,
                            "OAuth2 authorization callback missing or empty state parameter".into(),
                        ));
                    }
                }
            }

            None
        };
        Vec::from_iter(finding())
    }
}

/// The `name=value` pairs a query string carries, in the order they were
/// written, with percent-encoding left as the sender wrote it.
///
/// **This transcribes no production, which is why it lives beside its one
/// caller and not in a module named for one.** `query = *( pchar / "/" / "?" )`
/// generates the `&` and the `=` as ordinary data and says nothing about what
/// they separate; the `key=value` shape is something § 3.4 says query
/// components are *often used* to carry, which is a remark about practice and
/// not a grammar a reader may assume. The parameters this rule's sentences name
/// are written that way, so the reading is this rule's. The day a second rule
/// asks the same question, the two of them decide where the answer lives.
///
/// Empty names are kept, because a malformed query is exactly what this rule
/// reads; a pair with no `=` is a name with an empty value; and an empty element
/// between two `&` is skipped.
// cite(RFC 3986 § 3.4): "query       = *( pchar / "/" / "?" )"
// cite(RFC 3986 § 3.4): "as query components are often used to carry identifying information in the form of "key=value" pairs"
fn parse_query_string(s: &str) -> Vec<(String, String)> {
    let mut out = Vec::new();
    for pair in s.split('&') {
        if pair.is_empty() {
            continue;
        }
        let mut kv = pair.splitn(2, '=');
        let name = kv.next().unwrap_or("").to_string();
        let value = kv.next().unwrap_or("").to_string();
        out.push((name, value));
    }
    out
}

/// Registers this rule into the engine's auto-collected catalogue.
#[linkme::distributed_slice(crate::rules::REGISTERED_RULES)]
static REGISTRATION: &dyn crate::rules::Rule = &Oauth2CodeFlow;

#[cfg(test)]
mod tests {
    use super::*;
    use crate::test_helpers;

    fn make_tx(uri: &str) -> crate::http_transaction::HttpTransaction {
        let mut tx = test_helpers::make_test_transaction();
        tx.request.uri = uri.to_string();
        tx
    }

    #[test]
    fn auth_request_without_state_flagged() {
        let rule = Oauth2CodeFlow;
        let tx = make_tx("https://idp.example.com/authorize?response_type=code&client_id=1");
        let history = crate::transaction_history::TransactionHistory::empty();
        let v = crate::test_helpers::run_rule(
            &rule,
            &tx,
            &history,
            &crate::test_helpers::make_test_config_with_enabled_rules(&["oauth2_code_flow"]),
        )
        .unwrap();
        assert!(v.message.contains("missing or empty state"));
    }

    #[test]
    fn auth_request_with_state_ok() {
        let rule = Oauth2CodeFlow;
        let tx = make_tx("https://idp.example.com/authorize?response_type=code&state=xyz");
        let history = crate::transaction_history::TransactionHistory::empty();
        assert!(crate::test_helpers::run_rule(
            &rule,
            &tx,
            &history,
            &crate::test_helpers::make_test_config_with_enabled_rules(&["oauth2_code_flow"]),
        )
        .is_none());
    }

    #[test]
    fn callback_without_state_flagged() {
        let rule = Oauth2CodeFlow;
        let tx = make_tx("https://app.example.com/callback?code=abc");
        let history = crate::transaction_history::TransactionHistory::empty();
        let v = crate::test_helpers::run_rule(
            &rule,
            &tx,
            &history,
            &crate::test_helpers::make_test_config_with_enabled_rules(&["oauth2_code_flow"]),
        )
        .unwrap();
        assert!(v.message.contains("missing or empty state"));
    }

    #[test]
    fn callback_with_unseen_state_flagged() {
        let rule = Oauth2CodeFlow;
        let tx = make_tx("https://app.example.com/callback?code=abc&state=xyz");
        let history = crate::transaction_history::TransactionHistory::empty();
        let v = crate::test_helpers::run_rule(
            &rule,
            &tx,
            &history,
            &crate::test_helpers::make_test_config_with_enabled_rules(&["oauth2_code_flow"]),
        )
        .unwrap();
        assert!(v.message.contains("not seen"));
    }

    #[test]
    fn callback_with_matching_state_ok() {
        let rule = Oauth2CodeFlow;
        // initial auth request earlier in history
        let history =
            crate::transaction_history::TransactionHistory::from_transactions(vec![make_tx(
                "https://idp.example.com/authorize?response_type=code&state=xyz",
            )]);
        let tx = make_tx("https://app.example.com/callback?code=abc&state=xyz");
        assert!(crate::test_helpers::run_rule(
            &rule,
            &tx,
            &history,
            &crate::test_helpers::make_test_config_with_enabled_rules(&["oauth2_code_flow"]),
        )
        .is_none());
    }

    #[test]
    fn auth_and_callback_without_code_does_not_check_state() {
        let rule = Oauth2CodeFlow;
        // a request with state but not response_type=code shouldn't trigger
        let tx = make_tx("https://example.com/foo?state=xyz");
        let history = crate::transaction_history::TransactionHistory::empty();
        assert!(crate::test_helpers::run_rule(
            &rule,
            &tx,
            &history,
            &crate::test_helpers::make_test_config_with_enabled_rules(&["oauth2_code_flow"]),
        )
        .is_none());
    }

    #[test]
    fn auth_and_callback_with_fragments_are_handled() {
        let rule = Oauth2CodeFlow;
        // auth request has fragment after query, should still record state
        let history =
            crate::transaction_history::TransactionHistory::from_transactions(vec![make_tx(
                "https://idp.example.com/authorize?response_type=code&state=foo#frag",
            )]);
        let tx = make_tx("https://app.example.com/callback?code=abc&state=foo#bar");
        assert!(crate::test_helpers::run_rule(
            &rule,
            &tx,
            &history,
            &crate::test_helpers::make_test_config_with_enabled_rules(&["oauth2_code_flow"]),
        )
        .is_none());
    }

    #[test]
    fn auth_request_fragment_missing_state_flagged() {
        let rule = Oauth2CodeFlow;
        let tx = make_tx("https://idp.example.com/authorize?response_type=code#frag");
        let history = crate::transaction_history::TransactionHistory::empty();
        let v = crate::test_helpers::run_rule(
            &rule,
            &tx,
            &history,
            &crate::test_helpers::make_test_config_with_enabled_rules(&["oauth2_code_flow"]),
        )
        .unwrap();
        assert!(v.message.contains("missing or empty state"));
    }

    #[test]
    fn empty_state_value_flagged_both_sides() {
        let rule = Oauth2CodeFlow;
        // auth request with empty state
        let tx1 = make_tx("https://idp.example.com/authorize?response_type=code&state=");
        let history =
            crate::transaction_history::TransactionHistory::from_transactions(vec![tx1.clone()]);
        // callback with empty state should flag missing or empty
        let tx2 = make_tx("https://app.example.com/callback?code=123&state=");
        let v = crate::test_helpers::run_rule(
            &rule,
            &tx1,
            &crate::transaction_history::TransactionHistory::empty(),
            &crate::test_helpers::make_test_config_with_enabled_rules(&["oauth2_code_flow"]),
        )
        .unwrap();
        assert!(v.message.contains("missing or empty state"));
        let v2 = crate::test_helpers::run_rule(
            &rule,
            &tx2,
            &history,
            &crate::test_helpers::make_test_config_with_enabled_rules(&["oauth2_code_flow"]),
        )
        .unwrap();
        assert!(v2.message.contains("missing or empty state"));
    }

    /// Which entry answers for each leg of the flow — the two ends and the
    /// join between them.
    #[test]
    fn each_leg_of_the_flow_names_its_entry() {
        let cfg = crate::test_helpers::make_test_config_with_enabled_rules(&["oauth2_code_flow"]);
        let empty = crate::transaction_history::TransactionHistory::empty();

        let request = crate::test_helpers::run_rule(
            &Oauth2CodeFlow,
            &make_tx("/authorize?response_type=code&client_id=abc"),
            &empty,
            &cfg,
        )
        .expect("a finding");
        assert_eq!(request.violation, "oauth2_request_state_missing");

        let callback =
            crate::test_helpers::run_rule(&Oauth2CodeFlow, &make_tx("/cb?code=xyz"), &empty, &cfg)
                .expect("a finding");
        assert_eq!(callback.violation, "oauth2_callback_state_missing");

        let unseen = crate::test_helpers::run_rule(
            &Oauth2CodeFlow,
            &make_tx("/cb?code=xyz&state=nobody-sent-this"),
            &empty,
            &cfg,
        )
        .expect("a finding");
        assert_eq!(unseen.violation, "oauth2_state_conflicting");
    }

    #[test]
    fn validate_rules_with_valid_config() {
        let mut cfg = crate::config::Config::default();
        crate::test_helpers::enable_rule(&mut cfg, "oauth2_code_flow");
        crate::rules::validate_rules(&cfg).unwrap();
    }
    #[test]
    fn parse_query_string_basic() {
        let v = parse_query_string("");
        assert!(v.is_empty());
        let v = parse_query_string("a=1&b=2");
        assert_eq!(
            v,
            vec![
                ("a".to_string(), "1".to_string()),
                ("b".to_string(), "2".to_string())
            ]
        );
        let v = parse_query_string("foo");
        assert_eq!(v, vec![("foo".to_string(), "".to_string())]);
        let v = parse_query_string("x=&=y&z=3");
        assert_eq!(
            v,
            vec![
                ("x".to_string(), "".to_string()),
                ("".to_string(), "y".to_string()),
                ("z".to_string(), "3".to_string()),
            ]
        );
    }
}
