// SPDX-FileCopyrightText: 2026 Alexandre Gomes Gaigalas <alganet@gmail.com>
//
// SPDX-License-Identifier: ISC

use crate::helpers::headers::{
    combined_field_value_as_written, list_members_as_written, split_semicolons_respecting_quotes,
    trim_ows, valid_qvalue, validate_quoted_string,
};
use crate::lint::Violation;
use crate::rules::Rule;

#[derive(Debug, Clone)]
pub struct TeHeaderValid;

impl TeHeaderValid {
    /// One request's `TE` value, measured against the production the section that
    /// defines the field prints.
    ///
    /// The value is read as the sender wrote it: every `TE` line of the section joined
    /// into the one list they are, and every octet arriving as the `char` of the same
    /// value. `get_header_str` answered `None` for a value carrying `obs-text`, and
    /// this rule read that answer as "the request has no `TE` field" — silencing every
    /// member check *and* the connection-option MUST for the whole message.
    ///
    /// cite(RFC 9110 § 5.2): "When a field name is repeated within a section, its combined field value consists of the list of corresponding field line values within that section, concatenated in order, with each field line value separated by a comma."
    /// cite(RFC 9110 § 10.1.4): "The TE field value is a list of members, with each member (aside from "trailers") consisting of a transfer coding name token with an optional weight indicating the client's relative preference for that transfer coding (Section 12.4.2) and optional parameters for that transfer coding."
    fn check_members(&self, value: &str, config: &crate::rules::RuleConfig) -> Option<Violation> {
        let violation = |message: String| {
            Some(Violation {
                rule: self.id().to_string(),
                severity: config.severity,
                message,
            })
        };

        // The field's list construct, expanded for a sender. The outer brackets are
        // why a `TE:` carrying nothing is not reported: `#t-codings` is not
        // `1#t-codings`, so a list of no members is a list this production generates.
        // The HTTP/1.1 document does not leave that to inference — it says what an
        // empty value *means*, and prints `TE:` as one of its three examples of the
        // field in use.
        //
        // The trim is the value's, not a member's, and a different sentence licenses
        // it: § 5.5's MUST on the parser, which is why `TE: ` declares no members
        // rather than one empty one.
        //
        // cite(RFC 9110 § A): "TE = [ t-codings *( OWS "," OWS t-codings ) ]"
        // cite(RFC 9112 § 7.4): "If the TE field value is empty or if no TE field is present, the only acceptable transfer coding is chunked."
        // cite(RFC 9110 § 5.5): "A field value does not include leading or trailing whitespace.  When a specific version of HTTP allows such whitespace to appear in a message, a field parsing implementation MUST exclude such whitespace prior to evaluating the field value."
        if trim_ows(value).is_empty() {
            return None;
        }

        let mut saw_an_empty_element = false;

        // `list_members_as_written` and not `list_members`, the recipient's walk.
        // That one splits at every comma, so `TE: deflate;ext="a,b"` — one
        // member, one parameter — came apart into a second "member" of `b"`; and
        // it drops the empty elements § 5.6.1.1 forbids a sender from
        // generating, which is the finding below. The quote-aware half is right
        // for *this* field because the production quoted here puts a
        // `quoted-string` inside the element; a `#token` list would want the
        // naive split instead.
        //
        // cite(RFC 9110 § A): "transfer-parameter = token BWS "=" BWS ( token / quoted-string )"
        for member in list_members_as_written(value) {
            if member.is_empty() {
                // Reported after the members that are present, and reported as the
                // list's defect rather than the element's: there is no empty
                // `t-codings`, so what the sender generated is a member contributing
                // nothing to the list.
                //
                // cite(RFC 9110 § 5.6.1.1): "In any production that uses the list construct, a sender MUST NOT generate empty list elements."
                saw_an_empty_element = true;
                continue;
            }

            // Quote-aware for the same reason the comma split is: a `quoted-string`
            // parameter value may hold a semicolon.
            let segments = split_semicolons_respecting_quotes(member);

            // Every `;` the member's grammar prints is followed by something — a
            // `transfer-parameter` in `transfer-coding`, `"q="` in `weight` — so a
            // `;` with nothing after it is generated by neither. This was skipped
            // with a `continue`, and a `#[case]` asserted `chunked;` was fine.
            //
            // cite(RFC 9110 § A): "transfer-coding = token *( OWS ";" OWS transfer-parameter )"
            // cite(RFC 9110 § 12.4.2): "weight = OWS ";" OWS "q=" qvalue"
            for segment in segments.iter().skip(1) {
                if segment.is_empty() {
                    return violation(format!(
                        "TE member '{}' holds a ';' with no parameter after it",
                        member.escape_debug()
                    ));
                }
            }

            let primary = segments.first().copied().unwrap_or("");

            // `t-codings` is an alternation and `"trailers"` is the whole of its
            // first alternative: it takes no parameters, and no weight either, since
            // the alternative admitting both is the other one. ABNF string literals
            // are case-insensitive.
            //
            // cite(RFC 9110 § A): "t-codings = "trailers" / ( transfer-coding [ weight ] )"
            if primary.eq_ignore_ascii_case("trailers") {
                if let Some(extra) = segments.get(1) {
                    return violation(format!(
                        "TE member '{}' hangs '{}' off the 'trailers' keyword; the t-codings alternative that admits a parameter or a weight is the transfer-coding one",
                        member.escape_debug(),
                        extra.escape_debug()
                    ));
                }
                continue;
            }

            // The coding name itself is not measured here. `transfer-coding = token`,
            // and `transfer_coding_registered` already measures TE's
            // coding names against `tchar` — for both fields that carry one, with the
            // offending character and the coding name in the finding — and reports a
            // member that names no coding at all. The private predicate that used to
            // sit here accepted alphanumerics and `-` only, so `TE: x!bad` was
            // reported against a grammar the RFC does not have, with an example
            // published as "(invalid token)" and two `#[case]`s pinning it. That rule
            // also owns `chunked` in TE (RFC 9112 § 7.4's MUST NOT) and the registry
            // question; this one owns what follows the name.
            //
            // cite(RFC 9110 § A): "transfer-coding = token *( OWS ";" OWS transfer-parameter )"
            for parameter in segments.iter().skip(1) {
                if let Some(v) = self.check_parameter(member, parameter, config) {
                    return Some(v);
                }
            }
        }

        if saw_an_empty_element {
            return violation(format!(
                "TE header holds an empty member: '{}'",
                value.escape_debug()
            ));
        }

        None
    }

    /// The connection option § 10.1.4 requires beside the field — on the versions of
    /// HTTP that have one.
    ///
    /// The MUST is unconditional in its own sentence and the condition is one section
    /// away: `Connection` is how *some* versions carry control information, and the two
    /// that do not carry it forbid the field outright. Requiring it of an HTTP/2 or
    /// HTTP/3 request told an operator to add a field whose presence makes the message
    /// malformed — and `TE: trailers`, the one value those versions allow, was the case
    /// most likely to be reported.
    ///
    /// What the value may hold on those versions is their own documents' requirement,
    /// not this one's: `no_connection_specific_fields` reports it for both.
    ///
    /// cite(RFC 9110 § 7.6.1): "Note that some versions of HTTP prohibit the use of fields for such information, and therefore do not allow the Connection field."
    /// cite(RFC 9113 § 8.2.2): "An endpoint MUST NOT generate an HTTP/2 message containing connection-specific header fields."
    /// cite(RFC 9113 § 8.2.2): "The only exception to this is the TE header field, which MAY be present in an HTTP/2 request; when it is, it MUST NOT contain any value other than "trailers"."
    /// cite(RFC 9114 § 4.2): "An endpoint MUST NOT generate an HTTP/3 field section containing connection-specific fields; any message containing connection-specific fields MUST be treated as malformed."
    fn check_connection_option(
        &self,
        tx: &crate::http_transaction::HttpTransaction,
        config: &crate::rules::RuleConfig,
    ) -> Option<Violation> {
        // The major digit decides whether this version has a `Connection` field
        // to carry the option; `http_version` owns the production that reads it.
        let version = tx.request.version.as_str();
        if matches!(crate::http_version::major(version), Some(2 | 3)) {
            return None;
        }

        // The question is whether the sender listed the option, which is the
        // *recipient's* reading of a list — so the shared list reader is the right one
        // here, empty-element filter and all. Whether the `Connection` value is itself
        // well formed is `connection_header_tokens_valid`'s. Its lines are
        // joined first: an option written on a second `Connection` line is listed.
        //
        // cite(RFC 9110 § 10.1.4): "A sender of TE MUST also send a "TE" connection option within the Connection header field (Section 7.6.1) to inform intermediaries not to forward this field."
        // cite(RFC 9112 § 7.4): "Since the TE header field only applies to the immediate connection, a sender of TE MUST also send a "TE" connection option within the Connection header field (Section 7.6.1 of [HTTP]) in order to prevent the TE header field from being forwarded by intermediaries that do not support its semantics."
        let connection = combined_field_value_as_written(&tx.request.headers, "connection");
        if crate::helpers::headers::is_nominated_by_connection("te", connection.as_deref()) {
            return None;
        }

        Some(Violation {
            rule: self.id().to_string(),
            severity: config.severity,
            message:
                "Request carries a TE header field without a 'TE' connection option in Connection; \
                 TE applies to the immediate connection only, and the option is what stops an \
                 intermediary from forwarding it"
                    .into(),
        })
    }

    /// One `transfer-parameter` of one member — or the `weight`, which is not one.
    ///
    /// cite(RFC 9110 § A): "transfer-parameter = token BWS "=" BWS ( token / quoted-string )"
    fn check_parameter(
        &self,
        member: &str,
        parameter: &str,
        config: &crate::rules::RuleConfig,
    ) -> Option<Violation> {
        let violation = |message: String| {
            Some(Violation {
                rule: self.id().to_string(),
                severity: config.severity,
                message,
            })
        };

        // The `"="` is not optional in either production, so a segment written
        // without one is generated by neither: not by `transfer-parameter`, and not
        // by a `weight`, whose `"q="` is one literal.
        let Some((raw_name, raw_value)) = parameter.split_once('=') else {
            return violation(format!(
                "TE parameter '{}' in member '{}' has no value; neither a transfer-parameter nor a weight is written without an '='",
                parameter.escape_debug(),
                member.escape_debug()
            ));
        };

        let name = trim_ows(raw_name);
        let value = trim_ows(raw_value);

        // Removing whitespace from around the `=` is the recipient's MUST, and is what
        // the two trims above do. Whether *writing* it is a defect, and of what, is a
        // question about which production the segment belongs to — so it is asked in
        // each of the two branches below rather than once here, where the answer would
        // have been the `transfer-parameter` one for both.
        //
        // cite(RFC 9110 § 5.6.3): "The BWS rule is used where the grammar allows optional whitespace only for historical reasons.  A sender MUST NOT generate BWS in messages.  A recipient MUST parse for such bad whitespace and remove it before interpreting the protocol element."
        let whitespace_around_equals =
            name.len() != raw_name.len() || value.len() != raw_value.len();

        // `token = 1*tchar` has no empty alternative, so a parameter that is only an
        // `=` names nothing. `find_invalid_token_char` answers `None` for the empty
        // string — there is no offending character to point at — so without this the
        // member passed.
        //
        // cite(RFC 9110 § 5.6.2): "token = 1*tchar tchar = "!" / "#" / "$" / "%" / "&" / "'" / "*" / "+" / "-" / "." / "^" / "_" / "`" / "|" / "~" / DIGIT / ALPHA"
        if name.is_empty() {
            return violation(format!(
                "TE parameter '{}' in member '{}' names no parameter; a transfer-parameter's name is a token",
                parameter.escape_debug(),
                member.escape_debug()
            ));
        }

        // An octet at or above %x80 is `obs-text`, which `field-content` admits and
        // `token` does not — so it arrives here as a `char` outside the `tchar` set
        // and is reported as the parameter's defect rather than as a claim about the
        // message's encoding.
        if let Some(c) = crate::helpers::token::find_invalid_token_char(name) {
            return violation(format!(
                "TE parameter name '{}' in member '{}' holds invalid character '{}'; a name is a token",
                name.escape_debug(),
                member.escape_debug(),
                c.escape_debug()
            ));
        }

        // `q` is not a `transfer-parameter` at all: the grammar puts it outside
        // `transfer-coding`, as the `weight` that may follow one, and the HTTP/1.1
        // document calls it a pseudo-parameter and says the name is matched
        // case-insensitively.
        //
        // cite(RFC 9112 § 7.3): "The TE header field (Section 10.1.4 of [HTTP]) uses a pseudo-parameter named "q" as the rank value when multiple transfer codings are acceptable."
        // cite(RFC 9112 § 7.4): "When multiple transfer codings are acceptable, the client MAY rank the codings by preference using a case-insensitive "q" parameter (similar to the qvalues used in content negotiation fields; see Section 12.4.2 of [HTTP])."
        if name.eq_ignore_ascii_case("q") {
            // The weight is not a `transfer-parameter`, so the `BWS` its neighbours may
            // carry is not admitted here at all: `weight` prints `"q="` as one literal
            // with nothing optional inside it. Reporting this as bad whitespace would
            // name a sentence that is not about the construct — the same two-sentences,
            // one predicate shape as a member's trim and a value's.
            //
            // cite(RFC 9110 § 12.4.2): "weight = OWS ";" OWS "q=" qvalue"
            if whitespace_around_equals {
                return violation(format!(
                    "TE member '{}' writes whitespace around the weight's '='; the weight is OWS \";\" OWS \"q=\" qvalue, which admits none there",
                    member.escape_debug()
                ));
            }

            // The three-decimal cap the `qvalue` production carries is a MUST NOT of
            // its own, one paragraph below the grammar.
            //
            // cite(RFC 9110 § 12.4.2): "A sender of qvalue MUST NOT generate more than three digits after the decimal point."
            if !valid_qvalue(value) {
                return violation(format!(
                    "Invalid qvalue '{}' in TE member '{}'; a weight is 0 or 1 with at most three digits after the point",
                    value.escape_debug(),
                    member.escape_debug()
                ));
            }
            return None;
        }

        // Here the whitespace *is* `BWS`: the production prints it on both sides of the
        // `=`, for historical reasons and with a sender MUST NOT attached.
        if whitespace_around_equals {
            return violation(format!(
                "TE parameter '{}' in member '{}' writes whitespace around its '='; the production admits it there as BWS, which a sender must not generate",
                parameter.escape_debug(),
                member.escape_debug()
            ));
        }

        // `( token / quoted-string )` — the value is one or the other, and a value
        // opening with a DQUOTE is being written as the second.
        //
        // cite(RFC 9110 § 5.6.4): "quoted-string  = DQUOTE *( qdtext / quoted-pair ) DQUOTE"
        if value.starts_with('"') {
            if let Err(e) = validate_quoted_string(value) {
                return violation(format!(
                    "Invalid quoted-string parameter value '{}' in TE member '{}': {}",
                    value.escape_debug(),
                    member.escape_debug(),
                    e
                ));
            }
            return None;
        }

        // The other alternative is `token`, which is `1*tchar` on both counts: an
        // empty value is not one either.
        if value.is_empty() {
            return violation(format!(
                "TE parameter '{}' in member '{}' has an empty value; the alternatives are a token and a quoted-string, and neither is empty",
                parameter.escape_debug(),
                member.escape_debug()
            ));
        }

        if let Some(c) = crate::helpers::token::find_invalid_token_char(value) {
            return violation(format!(
                "TE parameter value '{}' for '{}' in member '{}' holds invalid character '{}'",
                value.escape_debug(),
                name.escape_debug(),
                member.escape_debug(),
                c.escape_debug()
            ));
        }

        None
    }
}

impl Rule for TeHeaderValid {
    fn id(&self) -> &'static str {
        "te_header_valid"
    }

    /// The field is a request field, and the response half of the rule exists only to
    /// say that a response carrying it is carrying something undefined — which still
    /// needs the response.
    ///
    /// cite(RFC 9110 § 10.1.4): "The "TE" header field describes capabilities of the client with regard to transfer codings and trailer sections."
    fn scope(&self) -> crate::rules::RuleScope {
        crate::rules::RuleScope::Both
    }

    fn check_transaction(
        &self,
        tx: &crate::http_transaction::HttpTransaction,
        _history: &crate::transaction_history::TransactionHistory,
        cfg: &crate::config::Config,
    ) -> Option<Violation> {
        let config = crate::rules::parse_rule_config(cfg, self.id()).ok()?;

        if let Some(resp) = &tx.response {
            // The field is defined in § 10.1, whose subject is stated in its first
            // sentence, and § 10.1.4 defines this one as describing the *client*.
            // Nothing measures a `TE` in a response, because no sentence gives one a
            // meaning there — which is also the whole of what this finding claims;
            // `description()` says so, since a reader is otherwise entitled to read a
            // finding as the report of a prohibition. Presence is asked of the
            // headers rather than of a decoded value: a value carrying `obs-text` is
            // still a `TE` field on the wire, and reading it through `to_str` made
            // the response look like one that has none.
            //
            // Asked only of the versions that state no prohibition of their own.
            // On HTTP/2 and HTTP/3 the exception restoring `TE` is written for a
            // *request*, so a response carrying one is a connection-specific
            // field and the message is malformed —
            // `no_connection_specific_fields` reports that, with the
            // version's own sentence. Reporting it here as well would be two
            // findings for one field, and the weaker of the two would be the one
            // saying RFC 9110 merely gives it no meaning.
            //
            // cite(RFC 9110 § 10.1): "The request header fields below provide additional information about the request context, including information about the user, user agent, and resource behind the request."
            // cite(RFC 9110 § 10.1.4): "The "TE" header field describes capabilities of the client with regard to transfer codings and trailer sections."
            // The gate is a condition on this branch and not an early return:
            // the request-side checks below are this rule's main body, and a
            // `return None` here would have taken them with it.
            if !matches!(crate::http_version::major(&resp.version), Some(2 | 3))
                && resp.headers.contains_key("te")
            {
                let value =
                    combined_field_value_as_written(&resp.headers, "te").unwrap_or_default();
                return Some(Violation {
                    rule: self.id().to_string(),
                    severity: config.severity,
                    message: format!(
                        "Response carries a TE header field: '{}'; TE is a request context field describing the client's capabilities, and RFC 9110 gives it no meaning in a response",
                        value.escape_debug()
                    ),
                });
            }
        }

        let value = combined_field_value_as_written(&tx.request.headers, "te")?;

        if let Some(v) = self.check_members(&value, &config) {
            return Some(v);
        }

        self.check_connection_option(tx, &config)
    }

    fn description(&self) -> &'static str {
        "Validates the `TE` request header field — the transfer codings a client is able to accept in a response, and whether it will keep a trailer section.\n\nThe field is `TE = [ t-codings *( OWS \",\" OWS t-codings ) ]` (RFC 9110 §A) and a member is `t-codings = \"trailers\" / ( transfer-coding [ weight ] )` (§10.1.4). `trailers` is a keyword occupying the whole of its alternative, so it takes neither a parameter nor a weight — the alternative that admits either is the other one. A coding may carry `transfer-parameter = token BWS \"=\" BWS ( token / quoted-string )` parameters and a `weight`, whose `q` is a `qvalue`: 0 or 1 with at most three digits after the point (§12.4.2), matched case-insensitively because RFC 9112 §7.3 says the pseudo-parameter's name is. Whitespace around a *parameter's* `=` is `BWS`, which the production admits for historical reasons only and which a sender MUST NOT generate (§5.6.3); around the *weight's* `=` it is not admitted at all, since `weight = OWS \";\" OWS \"q=\" qvalue` prints `q=` as one literal — the same three characters of whitespace, two productions, and only one of them has a sentence about bad whitespace to quote. No member may be empty (§5.6.1.1) — `TE: deflate,,gzip` is a list a sender must not generate — while an **empty field value** is a different thing and is not reported: `TE:` is a list of no members, and RFC 9112 §7.4 prints it as one of its three examples and says what it means (only `chunked` is acceptable).\n\n**The coding name itself is not measured here.** `transfer-coding` is a `token`, and `transfer_coding_registered` is the rule that reads the names `TE` and `Transfer-Encoding` carry: it reports a name that is not a token, a member naming no coding at all, an unrecognized name, and `chunked` in `TE` — which RFC 9112 §7.4 forbids outright, since a client cannot decline a coding that is always acceptable. This rule owns what follows the name.\n\nA sender of `TE` MUST also send a `TE` connection option within `Connection` (§10.1.4), which is what stops an intermediary from forwarding a field that applies to one hop. **That requirement is asked only of the versions of HTTP that have a `Connection` field.** HTTP/2 and HTTP/3 convey connection-specific metadata by other means, and an endpoint MUST NOT generate a message carrying the field at all (RFC 9113 §8.2.2, RFC 9114 §4.2) — so a request over those versions is not reported for omitting an option it is not allowed to send. What a `TE` value may hold there — `trailers` and nothing else — is those documents' requirement rather than this rule's; `no_connection_specific_fields` reports it for both of them.\n\nScope: this rule reads a request's header section, and a response's only to report that the field is there. Where the field appears on several lines in one section they are one value (§5.2), so an empty member written at a line boundary is an empty member. A value carrying an octet outside US-ASCII is measured rather than skipped: `obs-text` is an octet `field-content` admits and neither `token` nor `qvalue` does, so it is reported at the parameter that carried it instead of turning the whole field — and the connection-option requirement with it — into silence. Whether `TE` may appear in a **trailer** section is §6.5.1's question and `trailer_fields_valid`'s, which holds the table `TE` is listed in.\n\n**A response carrying `TE` is reported, and RFC 9110 states no prohibition.** §10.1 gathers the request context fields and §10.1.4 defines this one as describing the client's capabilities; no sentence gives a `TE` in a response a meaning, and none forbids one in so many words either. The finding says that and no more. **It is asked only of a response carried by HTTP/1.x.** Over HTTP/2 and HTTP/3 there is a MUST NOT — a response is not the request their exception is written for, so the field is connection-specific there and the message is malformed — and `no_connection_specific_fields` reports it on each with that version's own sentence, which is the stronger of the two readings. Reporting it here as well would be two findings for one field."
    }

    fn specifications(&self) -> &'static [crate::rules::SpecRef] {
        &[
            crate::rules::SpecRef {
                spec: "RFC 9110",
                section: Some("10.1.4"),
                url: "https://www.rfc-editor.org/rfc/rfc9110.html#section-10.1.4",
                note: "The field: what a member is, the grammar of its parameters, and the connection option a sender of TE must send beside it",
            },
            crate::rules::SpecRef {
                spec: "RFC 9110",
                section: Some("10.1"),
                url: "https://www.rfc-editor.org/rfc/rfc9110.html#section-10.1",
                note: "The section the field is defined in — request context fields. It is the whole of the ground for reporting a TE in a response, and it carries no modal",
            },
            crate::rules::SpecRef {
                spec: "RFC 9110",
                section: Some("A"),
                url: "https://www.rfc-editor.org/rfc/rfc9110.html#appendix-A",
                note: "The collected grammar, where the list construct is expanded for a sender — the form that shows both that the whole value may be empty and that a member may not",
            },
            crate::rules::SpecRef {
                spec: "RFC 9110",
                section: Some("12.4.2"),
                url: "https://www.rfc-editor.org/rfc/rfc9110.html#section-12.4.2",
                note: "`weight` and `qvalue`, and the MUST NOT on generating more than three digits after the point",
            },
            crate::rules::SpecRef {
                spec: "RFC 9110",
                section: Some("5.6.1.1"),
                url: "https://www.rfc-editor.org/rfc/rfc9110.html#section-5.6.1.1",
                note: "The sender's half of the list construct: no empty elements. The recipient's half (§5.6.1.2, ignore them) is a different party's requirement",
            },
            crate::rules::SpecRef {
                spec: "RFC 9110",
                section: Some("5.6.3"),
                url: "https://www.rfc-editor.org/rfc/rfc9110.html#section-5.6.3",
                note: "`BWS`: the whitespace around a transfer-parameter's `=`, which a recipient MUST remove and a sender MUST NOT write",
            },
            crate::rules::SpecRef {
                spec: "RFC 9110",
                section: Some("7.6.1"),
                url: "https://www.rfc-editor.org/rfc/rfc9110.html#section-7.6.1",
                note: "The `Connection` field the option is listed in, and the note that some versions of HTTP do not allow the field at all",
            },
            crate::rules::SpecRef {
                spec: "RFC 9112",
                section: Some("7.4"),
                url: "https://www.rfc-editor.org/rfc/rfc9112.html#section-7.4",
                note: "HTTP/1.1's own account of the field: what an empty value means, the `q` rank, the `chunked` MUST NOT, and why the connection option is required",
            },
            crate::rules::SpecRef {
                spec: "RFC 9112",
                section: Some("7.3"),
                url: "https://www.rfc-editor.org/rfc/rfc9112.html#section-7.3",
                note: "`q` is a pseudo-parameter rather than a transfer-parameter, and its name is case-insensitive",
            },
            crate::rules::SpecRef {
                spec: "RFC 9113",
                section: Some("8.2.2"),
                url: "https://www.rfc-editor.org/rfc/rfc9113.html#section-8.2.2",
                note: "HTTP/2 forbids the `Connection` field, and excepts `TE` in a request when it holds nothing but `trailers`",
            },
            crate::rules::SpecRef {
                spec: "RFC 9114",
                section: Some("4.2"),
                url: "https://www.rfc-editor.org/rfc/rfc9114.html#section-4.2",
                note: "The same for HTTP/3. `no_connection_specific_fields` is the rule that enforces the value restriction, on both versions",
            },
            crate::rules::SpecRef {
                spec: "RFC 9110",
                section: Some("6.5.1"),
                url: "https://www.rfc-editor.org/rfc/rfc9110.html#section-6.5.1",
                note: "What the `trailers` keyword says on the wire: the client will not discard a trailer section",
            },
        ]
    }

    fn examples(&self) -> &'static [crate::rules::Example] {
        use crate::rules::{Compliance, Example};
        &[
            Example {
                compliance: Compliance::Compliant,
                label: None,
                snippet: "GET /resource HTTP/1.1\nHost: example.com\nConnection: TE\nTE: trailers",
            },
            // These two published `TE: chunked;q=0.8`, one of them as the
            // *compliant* way to rank a coding. RFC 9112 § 7.4 says a client
            // MUST NOT send the chunked transfer coding name in TE at all --
            // chunked is always acceptable, so declining it is not something TE
            // can express. `transfer_coding_registered` reports it,
            // which left this rule publishing a snippet a sibling flags.
            // § 7.4's own example ranks `deflate`, and so do these now.
            Example {
                compliance: Compliance::Compliant,
                label: Some("(codings ranked by quality)"),
                snippet: "GET /resource HTTP/1.1\nHost: example.com\nConnection: keep-alive, TE\nTE: trailers, deflate;q=0.5",
            },
            Example {
                compliance: Compliance::NonCompliant,
                label: Some("(TE without Connection: TE)"),
                snippet: "GET /resource HTTP/1.1\nHost: example.com\nTE: deflate;q=0.8",
            },
            // This published `TE: x!bad` as "(invalid token)". `!` is a `tchar`,
            // so the value is a conforming `transfer-coding` name and the label
            // named a grammar no RFC has -- the rule's own private one, which
            // admitted alphanumerics and `-` only. A coding name is now
            // `transfer_coding_registered`'s to judge, so the
            // NonCompliant examples here are things this rule reports.
            Example {
                compliance: Compliance::NonCompliant,
                label: Some("(a weight on the trailers keyword)"),
                snippet: "GET /resource HTTP/1.1\nHost: example.com\nConnection: TE\nTE: trailers;q=0.5",
            },
            Example {
                compliance: Compliance::NonCompliant,
                label: Some("(an empty list element)"),
                snippet: "GET /resource HTTP/1.1\nHost: example.com\nConnection: TE\nTE: deflate,,gzip",
            },
            Example {
                compliance: Compliance::NonCompliant,
                label: Some("(TE in response)"),
                snippet: "HTTP/1.1 200 OK\nTE: trailers",
            },
        ]
    }
}

/// Registers this rule into the engine's auto-collected catalogue.
#[linkme::distributed_slice(crate::rules::REGISTERED_RULES)]
static REGISTRATION: &dyn crate::rules::Rule = &TeHeaderValid;

#[cfg(test)]
mod tests {
    use super::*;

    use hyper::header::HeaderValue;
    use rstest::rstest;

    /// Every request fixture in this module is built here, from raw octets.
    ///
    /// Three reasons for the one constructor. The field is a list however many lines
    /// carry it, so a fixture that can only write one line cannot state the case
    /// where the join is what creates the finding. The octets go in as octets:
    /// `HeaderValue::from_str` would refuse the `obs-text` this rule used to answer
    /// with silence. And the version is named at every call site rather than
    /// inherited, because whether the `Connection` requirement applies at all is a
    /// question about the version — the fixtures that did not say which version they
    /// were could not have caught that it was asked of every one of them.
    fn request(version: &str, te: &[&[u8]], connection: &[&[u8]]) -> Option<Violation> {
        let rule = TeHeaderValid;
        let mut tx = crate::test_helpers::make_test_transaction();
        tx.request.version = version.to_string();
        let mut hm = hyper::HeaderMap::new();
        for line in te {
            hm.append("te", HeaderValue::from_bytes(line).expect("field value"));
        }
        for line in connection {
            hm.append(
                hyper::header::CONNECTION,
                HeaderValue::from_bytes(line).expect("field value"),
            );
        }
        tx.request.headers = hm;
        rule.check_transaction(
            &tx,
            &crate::transaction_history::TransactionHistory::empty(),
            &crate::test_helpers::make_test_config_with_enabled_rules(&[rule.id()]),
        )
    }

    /// A conforming request: whatever the value, the connection option is there.
    fn te(value: &[u8]) -> Option<Violation> {
        request("HTTP/1.1", &[value], &[b"TE"])
    }

    fn response(te: &[u8]) -> Option<Violation> {
        let rule = TeHeaderValid;
        let mut tx = crate::test_helpers::make_test_transaction_with_response(200, &[]);
        let mut hm = hyper::HeaderMap::new();
        hm.append("te", HeaderValue::from_bytes(te).expect("field value"));
        tx.response.as_mut().expect("response").headers = hm;
        rule.check_transaction(
            &tx,
            &crate::transaction_history::TransactionHistory::empty(),
            &crate::test_helpers::make_test_config_with_enabled_rules(&[rule.id()]),
        )
    }

    /// The three values RFC 9112 § 7.4 prints as examples of the field in use, and
    /// the forms § 10.1.4's grammar generates around them.
    #[rstest]
    #[case(b"deflate")]
    #[case(b"")]
    #[case(b"trailers, deflate;q=0.5")]
    #[case(b"trailers")]
    #[case(b"TRAILERS")]
    #[case(b"deflate;q=0")]
    #[case(b"deflate;q=1.000")]
    #[case(b"deflate;Q=0.5")]
    #[case(b"gzip;ext=x")]
    #[case(b"gzip;ext=\"ok\"")]
    #[case(b"gzip;ext=x;q=0.5")]
    #[case(b" deflate , gzip ")]
    fn a_conforming_te_value_is_not_a_finding(#[case] value: &[u8]) {
        let v = te(value);
        assert!(v.is_none(), "{:?}: {v:?}", String::from_utf8_lossy(value));
    }

    /// `TE = [ t-codings *( OWS "," OWS t-codings ) ]`: a value with no members is a
    /// value this production generates, and RFC 9112 § 7.4 says what it means rather
    /// than treating it as malformed.
    #[rstest]
    #[case(b"")]
    #[case(b" ")]
    #[case(b"\t")]
    fn a_list_of_no_codings_is_a_list(#[case] value: &[u8]) {
        let v = te(value);
        assert!(v.is_none(), "{:?}: {v:?}", String::from_utf8_lossy(value));
    }

    /// The other half of the pair, which the shared list reader used to drop before
    /// the rule could see it.
    #[rstest]
    #[case(b"deflate,,gzip")]
    #[case(b"deflate,")]
    #[case(b",deflate")]
    #[case(b",")]
    fn an_empty_member_is_a_list_a_sender_must_not_generate(#[case] value: &[u8]) {
        let v = te(value).expect("violation");
        assert!(v.message.contains("empty member"), "{}", v.message);
    }

    /// The case that exists only after the lines are joined: neither line holds an
    /// empty member, and the value they make together does.
    #[test]
    fn an_empty_member_written_at_a_line_boundary_is_an_empty_member() {
        let v = request("HTTP/1.1", &[b"deflate," as &[u8], b"gzip"], &[b"TE"]).expect("violation");
        assert!(v.message.contains("empty member"), "{}", v.message);
    }

    #[test]
    fn two_lines_of_codings_are_one_list_and_not_a_finding() {
        let v = request("HTTP/1.1", &[b"deflate" as &[u8], b"gzip"], &[b"TE"]);
        assert!(v.is_none(), "{v:?}");
    }

    /// A comma inside a `quoted-string` parameter value is not a list separator, and
    /// neither is a semicolon: the naive splits cut this member into pieces and
    /// reported the pieces.
    #[rstest]
    #[case(b"gzip;ext=\"a,b\"")]
    #[case(b"gzip;ext=\"a;b\"")]
    #[case(b"gzip;ext=\"a,b\";q=0.5")]
    fn a_quoted_parameter_value_holds_the_separators_without_separating(#[case] value: &[u8]) {
        let v = te(value);
        assert!(v.is_none(), "{:?}: {v:?}", String::from_utf8_lossy(value));
    }

    /// `"trailers"` is the whole of its alternative in `t-codings`: the alternative
    /// that admits a parameter or a weight is the other one.
    /// The assertion is on the clause that distinguishes *this* finding: every finding
    /// about one of these members echoes the member, so `"trailers"` is in the message
    /// whichever branch produced it.
    #[rstest]
    #[case(b"trailers;foo=bar")]
    #[case(b"trailers;q=0.5")]
    #[case(b"deflate, trailers;foo=1")]
    fn the_trailers_keyword_takes_neither_parameter_nor_weight(#[case] value: &[u8]) {
        let v = te(value).expect("violation");
        assert!(
            v.message.contains("off the 'trailers' keyword"),
            "{}",
            v.message
        );
    }

    /// Every `;` in the member's grammar is followed by something. This was skipped
    /// with a `continue`, and a `#[case]` asserted it was fine.
    #[rstest]
    #[case(b"deflate;")]
    #[case(b"deflate;;q=0.5")]
    #[case(b"trailers;")]
    fn a_semicolon_with_nothing_after_it_is_generated_by_neither_production(#[case] value: &[u8]) {
        let v = te(value).expect("violation");
        assert!(v.message.contains("no parameter after it"), "{}", v.message);
    }

    /// `transfer-coding = token`, and `token` is wider than the alphanumerics and
    /// hyphens this rule used to require. Nothing here is a finding *of this rule*:
    /// `transfer_coding_registered` is what measures a coding name, for
    /// both of the fields that carry one.
    #[rstest]
    #[case(b"x!bad")]
    #[case(b"x_y")]
    #[case(b"foo.bar")]
    fn a_coding_name_is_measured_by_the_rule_that_owns_coding_names(#[case] value: &[u8]) {
        let v = te(value);
        assert!(v.is_none(), "{:?}: {v:?}", String::from_utf8_lossy(value));
    }

    #[rstest]
    #[case(b"deflate;q", "has no value")]
    #[case(b"deflate;foo", "has no value")]
    #[case(b"deflate;=1", "names no parameter")]
    #[case(b"deflate;foo=", "empty value")]
    #[case(b"deflate;bad name=1", "invalid character")]
    #[case(b"deflate;foo=bad@", "invalid character")]
    #[case(b"deflate;foo=\"bad", "quoted-string")]
    #[case(b"deflate;q=1.0000", "qvalue")]
    #[case(b"deflate;q=.5", "qvalue")]
    #[case(b"deflate;q=\"0.5\"", "qvalue")]
    fn a_parameter_the_production_does_not_generate_is_reported(
        #[case] value: &[u8],
        #[case] expected: &str,
    ) {
        let v = te(value).expect("violation");
        assert!(v.message.contains(expected), "{}", v.message);
    }

    /// `BWS` is whitespace a production admits for historical reasons; a recipient MUST
    /// remove it and a sender MUST NOT write it.
    #[rstest]
    #[case(b"deflate;ext = x")]
    #[case(b"deflate;ext =x")]
    #[case(b"deflate;ext= x")]
    fn whitespace_around_a_parameters_equals_is_bws(#[case] value: &[u8]) {
        let v = te(value).expect("violation");
        assert!(v.message.contains("as BWS"), "{}", v.message);
    }

    /// The weight is not a transfer-parameter and prints no `BWS`: `"q="` is one
    /// literal. Naming the same sentence for both would name one that is not about
    /// this construct.
    #[rstest]
    #[case(b"deflate;q =0.5")]
    #[case(b"deflate;q= 0.5")]
    #[case(b"deflate;Q = 0.5")]
    fn whitespace_around_the_weights_equals_is_not_bws(#[case] value: &[u8]) {
        let v = te(value).expect("violation");
        assert!(v.message.contains("the weight's '='"), "{}", v.message);
        assert!(!v.message.contains("BWS"), "{}", v.message);
    }

    /// An octet outside US-ASCII made the whole field invisible: the members went
    /// unmeasured *and* the connection-option MUST went unenforced, on the strength
    /// of a value the message plainly carried.
    #[test]
    fn an_octet_outside_us_ascii_reaches_the_check_that_owns_it() {
        let v = te(b"deflate;\xffoo=1").expect("violation");
        assert!(v.message.contains("invalid character"), "{}", v.message);
    }

    #[test]
    fn an_unreadable_value_is_still_a_te_field_for_the_connection_option() {
        let v = request("HTTP/1.1", &[b"\xff" as &[u8]], &[]).expect("violation");
        assert!(v.message.contains("connection option"), "{}", v.message);
    }

    /// The `OWS` trim is `OWS` only: %xA0 is `obs-text`, and trimming it would turn a
    /// member no production admits into an empty one — reporting the list for a
    /// defect the element has.
    #[test]
    fn obs_text_is_not_whitespace_and_is_not_trimmed_away() {
        let v = te(b"deflate;\xa0=1").expect("violation");
        assert!(v.message.contains("invalid character"), "{}", v.message);
    }

    #[rstest]
    #[case("HTTP/1.1")]
    #[case("HTTP/1.0")]
    fn a_sender_of_te_must_send_the_connection_option(#[case] version: &str) {
        let v = request(version, &[b"trailers" as &[u8]], &[]).expect("violation");
        assert!(v.message.contains("connection option"), "{}", v.message);
    }

    /// The versions that forbid the `Connection` field cannot be asked for one —
    /// and `TE: trailers`, the one value they allow, is the case most likely to be
    /// reported. What the value may hold there is those documents' requirement, and
    /// `no_connection_specific_fields` reports it for both of them.
    #[rstest]
    #[case("HTTP/2.0")]
    #[case("HTTP/2.0")]
    #[case("HTTP/3.0")]
    fn the_versions_that_prohibit_the_connection_field_are_not_asked_for_it(#[case] version: &str) {
        let v = request(version, &[b"trailers" as &[u8]], &[]);
        assert!(v.is_none(), "{version}: {v:?}");
    }

    /// Connection options are case-insensitive, and the field is a list however many
    /// lines carry it.
    #[rstest]
    #[case(&[b"tE" as &[u8]])]
    #[case(&[b"kEeP-aLiVe, te" as &[u8]])]
    #[case(&[b"keep-alive" as &[u8], b"TE"])]
    fn the_option_is_found_whichever_line_and_case_it_is_written_in(#[case] connection: &[&[u8]]) {
        let v = request("HTTP/1.1", &[b"trailers" as &[u8]], connection);
        assert!(v.is_none(), "{v:?}");
    }

    #[test]
    fn a_connection_field_naming_other_options_is_not_the_option() {
        let v = request(
            "HTTP/1.1",
            &[b"deflate;q=0.8" as &[u8]],
            &[b"keep-alive, Upgrade"],
        )
        .expect("violation");
        assert!(v.message.contains("connection option"), "{}", v.message);
    }

    /// The field is defined for requests. The response half of the rule says that and
    /// no more, which is why the message says it rather than reporting a prohibition.
    #[rstest]
    #[case(b"trailers")]
    #[case(b"")]
    #[case(b"\xff")]
    fn a_response_carrying_te_is_carrying_an_undefined_field(#[case] value: &[u8]) {
        let v = response(value).expect("violation");
        assert!(v.message.contains("request context field"), "{}", v.message);
    }

    /// The versions whose own documents make the same response a *malformed
    /// message* are left to the rule that carries their sentence, or one field
    /// draws two findings and the weaker one is this.
    #[rstest]
    #[case("HTTP/2.0")]
    #[case("HTTP/3.0")]
    fn a_response_on_a_version_with_its_own_prohibition_is_left_to_that_rule(
        #[case] version: &str,
    ) {
        let rule = TeHeaderValid;
        let mut tx = crate::test_helpers::make_test_transaction_with_response(200, &[]);
        let resp = tx.response.as_mut().expect("response");
        resp.version = version.to_string();
        resp.headers = crate::test_helpers::make_headers_from_pairs(&[("te", "trailers")]);

        let v = rule.check_transaction(
            &tx,
            &crate::transaction_history::TransactionHistory::empty(),
            &crate::test_helpers::make_test_config_with_enabled_rules(&[rule.id()]),
        );
        assert!(v.is_none(), "{v:?}");
    }

    /// That gate is a condition on the response branch, not an early return —
    /// the difference is every request-side finding in this rule. Written as a
    /// `return None` it would have silenced them all whenever the response
    /// arrived on one of those versions.
    #[rstest]
    #[case("HTTP/2.0")]
    #[case("HTTP/3.0")]
    fn the_response_gate_does_not_silence_the_request_half(#[case] response_version: &str) {
        let rule = TeHeaderValid;
        let mut tx = crate::test_helpers::make_test_transaction_with_response(200, &[]);
        tx.request.version = "HTTP/1.1".into();
        tx.request.headers =
            crate::test_helpers::make_headers_from_pairs(&[("te", "deflate;;q=0.5")]);
        let resp = tx.response.as_mut().expect("response");
        resp.version = response_version.to_string();
        resp.headers = crate::test_helpers::make_headers_from_pairs(&[("te", "trailers")]);

        let v = rule.check_transaction(
            &tx,
            &crate::transaction_history::TransactionHistory::empty(),
            &crate::test_helpers::make_test_config_with_enabled_rules(&[rule.id()]),
        );
        assert!(v.is_some(), "the request's own TE defect went unreported");
    }

    #[test]
    fn a_response_without_te_is_not_a_finding() {
        let rule = TeHeaderValid;
        let tx = crate::test_helpers::make_test_transaction_with_response(200, &[]);
        let v = rule.check_transaction(
            &tx,
            &crate::transaction_history::TransactionHistory::empty(),
            &crate::test_helpers::make_test_config_with_enabled_rules(&[rule.id()]),
        );
        assert!(v.is_none(), "{v:?}");
    }

    #[test]
    fn a_request_without_te_is_not_a_finding() {
        let v = request("HTTP/1.1", &[], &[]);
        assert!(v.is_none(), "{v:?}");
    }

    #[rstest]
    #[case("1", true)]
    #[case("1.000", true)]
    #[case("1.0000", false)]
    #[case("0", true)]
    #[case("0.0", true)]
    // `0*3DIGIT` is satisfied by no digits, so a point with nothing after
    // it conforms. This case asserted the helper's old enumeration.
    #[case("0.", true)]
    #[case("1.", true)]
    #[case("0.123", true)]
    #[case("0.1234", false)]
    #[case(" 0.5 ", true)]
    fn check_qvalue_cases(#[case] s: &str, #[case] expected: bool) {
        assert_eq!(crate::helpers::headers::valid_qvalue(s), expected);
    }

    /// Nothing ran a published snippet through the rule that published it, and one of
    /// them was labelled for a finding the rule cannot emit: `TE: x!bad` under
    /// "(invalid token)", where `!` is a `tchar` and the value is a conforming coding
    /// name.
    #[test]
    fn published_examples_are_judged_the_way_they_are_labelled() {
        use crate::rules::{Compliance, Rule as _};

        let rule = TeHeaderValid;
        let mut saw_a_finding = false;
        for ex in rule.examples() {
            let mut lines = ex.snippet.lines();
            let start_line = lines.next().expect("a message has a start line");
            let fields: Vec<(&str, &[u8])> = lines
                .map(|line| {
                    let (name, value) = line
                        .split_once(": ")
                        .unwrap_or_else(|| panic!("not a field line: {line:?}"));
                    (name, value.as_bytes())
                })
                .collect();

            let found = if start_line.starts_with("HTTP/") {
                let mut tx = crate::test_helpers::make_test_transaction_with_response(200, &[]);
                let resp = tx.response.as_mut().expect("response");
                let mut hm = hyper::HeaderMap::new();
                for (name, value) in &fields {
                    hm.append(
                        name.parse::<hyper::header::HeaderName>().expect("name"),
                        HeaderValue::from_bytes(value).expect("value"),
                    );
                }
                resp.headers = hm;
                rule.check_transaction(
                    &tx,
                    &crate::transaction_history::TransactionHistory::empty(),
                    &crate::test_helpers::make_test_config_with_enabled_rules(&[rule.id()]),
                )
            } else {
                let version = start_line
                    .rsplit(' ')
                    .next()
                    .expect("a request line ends in a version");
                let te: Vec<&[u8]> = fields
                    .iter()
                    .filter(|(n, _)| n.eq_ignore_ascii_case("te"))
                    .map(|(_, v)| *v)
                    .collect();
                let connection: Vec<&[u8]> = fields
                    .iter()
                    .filter(|(n, _)| n.eq_ignore_ascii_case("connection"))
                    .map(|(_, v)| *v)
                    .collect();
                request(version, &te, &connection)
            };

            match ex.compliance {
                Compliance::Compliant => assert!(
                    found.is_none(),
                    "rule reports its Compliant example {:?}: {found:?}",
                    ex.snippet
                ),
                Compliance::NonCompliant => {
                    assert!(
                        found.is_some(),
                        "rule accepts its NonCompliant example {:?}",
                        ex.snippet
                    );
                    saw_a_finding = true;
                }
            }
        }
        assert!(saw_a_finding, "no NonCompliant example produced a finding");
    }

    /// A rule cannot see what is wrong with a value it only reads part of. Every `TE`
    /// value published here holds a coding name, and the rule that judges coding names
    /// is a different one — which is how `TE: chunked;q=0.8` came to be published as
    /// the compliant way to rank a coding, one section after RFC 9112 § 7.4 forbids
    /// naming `chunked` in this field at all.
    ///
    /// The config is built here rather than with `make_test_config_with_enabled_rules`
    /// because that rule requires an `allowed` array: without one it returns `None` for
    /// every input and this guard passes by declining to run.
    #[test]
    fn published_te_values_are_accepted_by_the_rule_that_owns_coding_names() {
        use crate::rules::{Compliance, Rule as _};

        let owner = super::super::transfer_coding_registered::TransferCodingRegistered;
        let mut cfg = crate::config::Config::default();
        cfg.rules.insert(
            "transfer_coding_registered".into(),
            toml::Value::Table({
                let mut t = toml::map::Map::new();
                t.insert("enabled".into(), toml::Value::Boolean(true));
                t.insert("severity".into(), toml::Value::String("warn".into()));
                t.insert(
                    "allowed".into(),
                    toml::Value::Array(vec![
                        toml::Value::String("chunked".into()),
                        toml::Value::String("gzip".into()),
                        toml::Value::String("deflate".into()),
                        toml::Value::String("compress".into()),
                    ]),
                );
                t
            }),
        );

        for ex in TeHeaderValid.examples() {
            if ex.compliance != Compliance::Compliant {
                continue;
            }
            for line in ex.snippet.lines() {
                let Some((name, value)) = line.split_once(": ") else {
                    continue;
                };
                if !name.eq_ignore_ascii_case("te") {
                    continue;
                }
                let mut tx = crate::test_helpers::make_test_transaction();
                tx.request.headers = crate::test_helpers::make_headers_from_pairs(&[("te", value)]);
                let found = owner.check_transaction(
                    &tx,
                    &crate::transaction_history::TransactionHistory::empty(),
                    &cfg,
                );
                assert!(
                    found.is_none(),
                    "published TE value {value:?} is reported by the rule that owns coding names: {found:?}"
                );
            }
        }
    }

    #[test]
    fn validate_rules_with_valid_config() -> anyhow::Result<()> {
        let mut cfg = crate::config::Config::default();
        crate::test_helpers::enable_rule(&mut cfg, "te_header_valid");
        crate::rules::validate_rules(&cfg)?;
        Ok(())
    }

    #[test]
    fn scope_is_both() {
        let rule = TeHeaderValid;
        assert_eq!(rule.scope(), crate::rules::RuleScope::Both);
    }
}
