// SPDX-FileCopyrightText: 2026 Alexandre Gomes Gaigalas <alganet@gmail.com>
//
// SPDX-License-Identifier: ISC

//! Configuration generator: renders `config_example.toml` from the catalogue.
//!
//! The file used to be hand-maintained, which made it the one place a rule's
//! shipped example lived apart from the rule. Two gates already read it —
//! `config_example_includes_all_rules` and
//! `every_rule_prepares_under_the_example_config` — so a missing section was
//! caught, but a *wrong* one never was: nothing could compare an example
//! against the rule it configures, because the rule said nothing about it.
//! [`RuleMeta::config_example`](lint_http_rules::rules::RuleMeta::config_example)
//! is that statement, and this renders it.
//!
//! Everything above the first `[rules.*]` section is [`PREAMBLE`]: transport
//! policy belonging to `lint-http-proxy`, which no rule knows about and no rule
//! can therefore generate.
//!
//! [`render`] is pure and deterministic, so the `config_example_matches_generated`
//! gate can diff it against the checked-in file. Run `cargo xtask genconfig`
//! (or `just genconfig`) to fix drift.

use lint_http_rules::rules::all_rules;
use lint_http_rules::violations::{ViolationDef, VIOLATIONS};
use std::path::Path;

/// Everything above the first `[rules.*]` section, verbatim.
///
/// The `[general]` and `[tls]` tables are `lint-http-proxy`'s
/// `GeneralConfig`/`TlsConfig`, and their prose is the only documentation of
/// several keys that appear nowhere else. Generating it would mean reading
/// doc comments off a struct in a crate this one does not depend on; keeping
/// it here, beside the renderer, is the same choice `gendocs` makes for its
/// SPDX header and index blurb.
///
/// The `REUSE-IgnoreStart`/`REUSE-IgnoreEnd` markers stop `reuse lint` from
/// reading the embedded tag as this source file's own license header — the ISC
/// tag at the top is that.
// REUSE-IgnoreStart
const PREAMBLE: &str = r#"# SPDX-FileCopyrightText: 2025 Alexandre Gomes Gaigalas <alganet@gmail.com>
#
# SPDX-License-Identifier: ISC

# Generated by `cargo xtask genconfig`. Do not edit.
#
# The `[general]` and `[tls]` sections are the generator's own preamble —
# transport policy, which no rule knows about. Every `[rules.*]` section below
# is rendered from that rule's `config_example()` metadata, so a change to a
# rule's example belongs in `lint-http-rules/src/rules/<id>.rs`.
#
# The `[violations.*]` sections after them are the defects those rules report,
# each shown at the default severity its catalogue entry carries. They are
# overrides: deleting one changes nothing, editing one changes what that single
# defect reports at.

[general]
listen = "127.0.0.1:3000"
captures = "captures.jsonl"
ttl_seconds = 300
captures_seed = false
# When true, captured request/response bodies are included in the captures JSONL
# file as base64 strings. Bodies are still captured in memory for rules; this
# option only affects serialization to the captures file.
captures_include_body = false
# Maximum body bytes the proxy will buffer per request or response.
# Over-limit request bodies are rejected with 413; over-limit response bodies
# abort the exchange with 502. The captured transaction is marked with
# request_body_over_limit / response_body_over_limit. Default: 64 MiB.
# max_body_bytes = 67108864
# Maximum body bytes captured into the transaction (for rules) and the captures
# file. Bodies are forwarded in full; only the captured copy is bounded to this
# prefix, after which the body is marked truncated. Default: 1 MiB.
# captures_max_body_bytes = 1048576
# Maximum simultaneous live TCP connections; further connections wait for a
# slot rather than being accepted unboundedly. Default: 1024.
# max_connections = 1024
# On shutdown (Ctrl-C), seconds to wait for in-flight handlers to drain before
# exiting anyway. Default: 30.
# shutdown_timeout_seconds = 30
# Maximum protocol events per connection/session key for protocol-level rules
# (e.g. WebSocket frame sequencing). Larger values let rules detect violations
# across more frames but use more memory. Default: 200.
# max_protocol_event_history = 200
# Optional HTTP/3 (QUIC) listen address. Requires TLS enabled.
# h3_listen = "127.0.0.1:3443"
# Server name (SNI) for the HTTP/3 TLS certificate. Clients must connect
# using this name. Defaults to "localhost" when omitted.
# h3_server_name = "proxy.example.com"
# Forward to origins over HTTP/3 (QUIC) when they are known to speak it. This is
# the outbound (proxy->origin) leg, independent of h3_listen above. Only origins
# whose authority is in h3_upstream_authorities are attempted over H3; all others
# use the H1/H2 client. Default: false.
# h3_upstream_enabled = false
# Origins always tried over H3 (pre-seeds discovery; the first request to an
# origin can't have learned Alt-Svc yet).
# h3_upstream_authorities = ["origin.example.com:443"]
# Origins that must never use H3, even if Alt-Svc advertises it.
# h3_upstream_denylist = ["legacy.example.com:443"]
# Trust an origin's Alt-Svc header to discover an H3 endpoint at runtime. A
# discovered endpoint is still only used once its cert validates for the origin
# authority. Set false to route H3 solely from h3_upstream_authorities. Default: true.
# h3_upstream_trust_alt_svc = true
# UDP bind address for the H3 upstream client. Default: "[::]:0" -- the IPv6
# wildcard, which quinn makes dual-stack (it clears only_v6 and v4-maps an IPv4
# peer), so both families are reachable. Setting this to an IPv4 address makes
# origins that resolve to IPv6 unreachable over H3; they fall back to H1/H2.
# h3_upstream_bind = "[::]:0"
# Extra CA PEM files to trust for origin H3 endpoint certificates (private CAs),
# in addition to the platform trust store.
# h3_upstream_extra_ca_certs = ["/etc/lint-http/origin-ca.pem"]
# Timeout (ms) for the H3 upstream connect/handshake before falling back to
# H1/H2. Default: 5000.
# h3_upstream_connect_timeout_ms = 5000
# Timeout (ms) for the H3 upstream response head (first origin byte) once the
# request is sent. Bounded separately from the connect timeout — this is origin
# think-time, so it is set far more generously to avoid dropping a slow-but-
# healthy origin. An idempotent bodyless request that hits it is retried on
# H1/H2; anything else returns 502. Default: 30000.
# h3_upstream_response_timeout_ms = 30000
# Base backoff (seconds) for the H3 negative cache: after a connect/handshake
# failure an origin is not retried over H3 until this window (doubling per
# consecutive failure) passes. Default: 30.
# h3_upstream_negative_ttl_seconds = 30
# Idle time (ms) after which a pooled H3 connection is evicted; kept under the
# QUIC idle timeout so only live connections are reused. Default: 25000.
# h3_upstream_pool_idle_ms = 25000
# Maximum pooled H3 connections (one per origin); LRU-evicted past this.
# Default: 256.
# h3_upstream_pool_max = 256
# Serve the live capture stream at GET /_lint_http/stream (Server-Sent Events,
# one event per transaction as it commits). Exposes all proxied traffic to
# anyone who can reach the proxy port, so it is opt-in. Default: false.
# live_stream_enabled = false

[tls]
enabled = true
ca_cert_path = "ca.crt"
ca_key_path = "ca.key"
passthrough_domains = ["example.com"]
suppress_headers = ["X-Sensitive-Header"]
"#;
// REUSE-IgnoreEnd

/// One `[violations.<id>]` section: the def's own default severity, written
/// out so the file an operator copies shows what every defect reports at and
/// where to change it.
///
/// The value is what the catalogue already resolves to, which makes the whole
/// table redundant by construction — and that is the point of shipping it.
/// A severity default lives in code precisely because a catalogue this size
/// cannot be hand-answered; the generated file is how it stays visible anyway.
fn violation_section(def: &ViolationDef) -> String {
    format!(
        "[violations.{}]\n# {}\nseverity = \"{}\"\n",
        def.id,
        def.title,
        def.default_severity.name(),
    )
}

/// The whole file, as bytes on disk: the preamble, then one `[rules.<id>]`
/// section per catalogue entry in [`all_rules`] order (transaction rules by id,
/// then protocol rules by id), then one `[violations.<id>]` section per defect
/// in [`VIOLATIONS`] order, every section separated by a blank line.
///
/// The rule tables come first and the violation tables after, rather than each
/// defect under the rule that reports it: a defect is not owned by one rule,
/// and TOML would read a `[violations.x]` header between two `[rules.*]`
/// headers as ending the rule table above it anyway.
///
/// Every header is rendered from an id rather than stored, so a section can
/// never name something other than what its body configures.
pub fn render() -> String {
    let mut out = String::from(PREAMBLE);
    for rule in all_rules() {
        out.push('\n');
        out.push_str(&format!("[rules.{}]\n", rule.id()));
        out.push_str(rule.config_example().trim_end_matches('\n'));
        out.push('\n');
    }
    for def in VIOLATIONS.iter() {
        out.push('\n');
        out.push_str(&violation_section(def));
    }
    out
}

/// Write [`render`] to `path`.
pub fn write(path: &Path) -> anyhow::Result<()> {
    std::fs::write(path, render())?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use lint_http_rules::rules::{PROTOCOL_RULES, RULES};

    #[test]
    fn render_starts_with_the_preamble_and_carries_the_last_rule() {
        let out = render();
        assert!(out.starts_with("# SPDX-FileCopyrightText"));
        assert!(out.contains("\n[tls]\n"));
        let last = all_rules().last().expect("catalogue is non-empty");
        assert!(
            out.contains(&format!("[rules.{}]\n{}", last.id(), last.config_example())),
            "the last rule's section is rendered whole"
        );
        assert!(out.ends_with('\n'), "the file ends with one newline");
    }

    /// What a `[violations.*]` section looks like, asserted against a def built
    /// here rather than one out of the catalogue: this is the shape of the
    /// section, and it should not change when the first real defect lands or
    /// when the catalogue is reordered.
    #[test]
    fn a_violation_section_is_its_id_title_and_default_severity() {
        let def = ViolationDef {
            id: "example_field_empty",
            title: "Example field is present but empty",
            message: "Example field is present but empty",
            default_severity: lint_http_rules::lint::Severity::Error,
            spec: None,
        };
        assert_eq!(
            violation_section(&def),
            "[violations.example_field_empty]\n\
             # Example field is present but empty\n\
             severity = \"error\"\n",
        );
    }

    /// Every defect is configurable by name, and named once. The catalogue is
    /// empty until the first subject moves over, which makes this vacuous now
    /// and load-bearing the moment it is not: a def that never reaches the file
    /// is a severity nobody can find, let alone change.
    #[test]
    fn render_emits_one_section_per_violation() {
        let out = render();
        assert_eq!(out.matches("\n[violations.").count(), VIOLATIONS.len());
        for def in VIOLATIONS.iter() {
            assert_eq!(
                out.matches(&format!("\n[violations.{}]\n", def.id)).count(),
                1,
                "{} should head exactly one section",
                def.id
            );
        }
    }

    /// Every rule contributes exactly one section, headed by its own id. The
    /// count is what catches a body that opens its own `[rules.*]` header —
    /// which would configure the wrong rule and pass a `contains` check.
    #[test]
    fn render_emits_one_section_per_rule() {
        let out = render();
        assert_eq!(
            out.matches("\n[rules.").count(),
            RULES.len() + PROTOCOL_RULES.len(),
        );
        for rule in all_rules() {
            assert_eq!(
                out.matches(&format!("\n[rules.{}]\n", rule.id())).count(),
                1,
                "{} should head exactly one section",
                rule.id()
            );
        }
    }

    /// A section body is the rule's, unedited — so the comment a rule writes
    /// to explain an option reaches the file it explains.
    #[test]
    fn render_carries_a_rules_own_comment() {
        let rule = all_rules()
            .find(|r| r.id() == "keep_alive_header_valid")
            .expect("keep_alive_header_valid registered");
        assert!(rule.config_example().contains("max_timeout_seconds"));
        assert!(render().contains(&format!("[rules.{}]\n{}", rule.id(), rule.config_example())));
    }

    /// Drift gate, the `config_example.toml` twin of `docs_match_generated`:
    /// the checked-in file must equal what the catalogue renders. Editing a
    /// rule's `config_example()` without regenerating fails CI.
    ///
    /// The floor assertion is not decoration. The catalogue reaches this crate
    /// across an rlib boundary through `linkme`, and an empty one would render
    /// the preamble alone — which fails loudly here, rather than quietly
    /// deleting 193 sections the next time someone runs the fixer.
    #[test]
    fn config_example_matches_generated() {
        assert!(
            !RULES.is_empty(),
            "catalogue did not collect in the xtask link config — this gate would compare \
             against a file with no rules in it",
        );
        let path = crate::repo_root().join("config_example.toml");
        let on_disk = std::fs::read_to_string(&path).expect("config_example.toml");
        assert!(
            on_disk == render(),
            "config_example.toml is out of date — run `cargo xtask genconfig`"
        );
    }
}
